function init(self)
	local spritedesc = {
		tile_set = "my tileset",
		default_animation = "",
		material = "",
		slice9 = { x = 2, y = 1.5, z = 1, w = 1 },
		blend_mode = ddf.DM_GAME_SYSTEM_DDF__SPRITE_DESC__BLEND_MODE_BLEND_MODE_ADD
	}
	pprint(spritedesc)
	local encoded = ddf.encode_dmgamesystemddf_spritedesc(spritedesc)
	local decoded = ddf.decode_dmgamesystemddf_spritedesc(encoded)
	pprint(decoded)
end
