/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: gameobject/gameobject_ddf.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "gameobject/gameobject_ddf.pb-c.h"
void   dm_game_object_ddf__property_desc__init
                     (DmGameObjectDDF__PropertyDesc         *message)
{
  static const DmGameObjectDDF__PropertyDesc init_value = DM_GAME_OBJECT_DDF__PROPERTY_DESC__INIT;
  *message = init_value;
}
size_t dm_game_object_ddf__property_desc__get_packed_size
                     (const DmGameObjectDDF__PropertyDesc *message)
{
  assert(message->base.descriptor == &dm_game_object_ddf__property_desc__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t dm_game_object_ddf__property_desc__pack
                     (const DmGameObjectDDF__PropertyDesc *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &dm_game_object_ddf__property_desc__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t dm_game_object_ddf__property_desc__pack_to_buffer
                     (const DmGameObjectDDF__PropertyDesc *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &dm_game_object_ddf__property_desc__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
DmGameObjectDDF__PropertyDesc *
       dm_game_object_ddf__property_desc__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (DmGameObjectDDF__PropertyDesc *)
     protobuf_c_message_unpack (&dm_game_object_ddf__property_desc__descriptor,
                                allocator, len, data);
}
void   dm_game_object_ddf__property_desc__free_unpacked
                     (DmGameObjectDDF__PropertyDesc *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &dm_game_object_ddf__property_desc__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   dm_game_object_ddf__component_desc__init
                     (DmGameObjectDDF__ComponentDesc         *message)
{
  static const DmGameObjectDDF__ComponentDesc init_value = DM_GAME_OBJECT_DDF__COMPONENT_DESC__INIT;
  *message = init_value;
}
size_t dm_game_object_ddf__component_desc__get_packed_size
                     (const DmGameObjectDDF__ComponentDesc *message)
{
  assert(message->base.descriptor == &dm_game_object_ddf__component_desc__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t dm_game_object_ddf__component_desc__pack
                     (const DmGameObjectDDF__ComponentDesc *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &dm_game_object_ddf__component_desc__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t dm_game_object_ddf__component_desc__pack_to_buffer
                     (const DmGameObjectDDF__ComponentDesc *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &dm_game_object_ddf__component_desc__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
DmGameObjectDDF__ComponentDesc *
       dm_game_object_ddf__component_desc__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (DmGameObjectDDF__ComponentDesc *)
     protobuf_c_message_unpack (&dm_game_object_ddf__component_desc__descriptor,
                                allocator, len, data);
}
void   dm_game_object_ddf__component_desc__free_unpacked
                     (DmGameObjectDDF__ComponentDesc *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &dm_game_object_ddf__component_desc__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   dm_game_object_ddf__embedded_component_desc__init
                     (DmGameObjectDDF__EmbeddedComponentDesc         *message)
{
  static const DmGameObjectDDF__EmbeddedComponentDesc init_value = DM_GAME_OBJECT_DDF__EMBEDDED_COMPONENT_DESC__INIT;
  *message = init_value;
}
size_t dm_game_object_ddf__embedded_component_desc__get_packed_size
                     (const DmGameObjectDDF__EmbeddedComponentDesc *message)
{
  assert(message->base.descriptor == &dm_game_object_ddf__embedded_component_desc__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t dm_game_object_ddf__embedded_component_desc__pack
                     (const DmGameObjectDDF__EmbeddedComponentDesc *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &dm_game_object_ddf__embedded_component_desc__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t dm_game_object_ddf__embedded_component_desc__pack_to_buffer
                     (const DmGameObjectDDF__EmbeddedComponentDesc *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &dm_game_object_ddf__embedded_component_desc__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
DmGameObjectDDF__EmbeddedComponentDesc *
       dm_game_object_ddf__embedded_component_desc__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (DmGameObjectDDF__EmbeddedComponentDesc *)
     protobuf_c_message_unpack (&dm_game_object_ddf__embedded_component_desc__descriptor,
                                allocator, len, data);
}
void   dm_game_object_ddf__embedded_component_desc__free_unpacked
                     (DmGameObjectDDF__EmbeddedComponentDesc *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &dm_game_object_ddf__embedded_component_desc__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   dm_game_object_ddf__prototype_desc__init
                     (DmGameObjectDDF__PrototypeDesc         *message)
{
  static const DmGameObjectDDF__PrototypeDesc init_value = DM_GAME_OBJECT_DDF__PROTOTYPE_DESC__INIT;
  *message = init_value;
}
size_t dm_game_object_ddf__prototype_desc__get_packed_size
                     (const DmGameObjectDDF__PrototypeDesc *message)
{
  assert(message->base.descriptor == &dm_game_object_ddf__prototype_desc__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t dm_game_object_ddf__prototype_desc__pack
                     (const DmGameObjectDDF__PrototypeDesc *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &dm_game_object_ddf__prototype_desc__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t dm_game_object_ddf__prototype_desc__pack_to_buffer
                     (const DmGameObjectDDF__PrototypeDesc *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &dm_game_object_ddf__prototype_desc__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
DmGameObjectDDF__PrototypeDesc *
       dm_game_object_ddf__prototype_desc__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (DmGameObjectDDF__PrototypeDesc *)
     protobuf_c_message_unpack (&dm_game_object_ddf__prototype_desc__descriptor,
                                allocator, len, data);
}
void   dm_game_object_ddf__prototype_desc__free_unpacked
                     (DmGameObjectDDF__PrototypeDesc *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &dm_game_object_ddf__prototype_desc__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   dm_game_object_ddf__component_property_desc__init
                     (DmGameObjectDDF__ComponentPropertyDesc         *message)
{
  static const DmGameObjectDDF__ComponentPropertyDesc init_value = DM_GAME_OBJECT_DDF__COMPONENT_PROPERTY_DESC__INIT;
  *message = init_value;
}
size_t dm_game_object_ddf__component_property_desc__get_packed_size
                     (const DmGameObjectDDF__ComponentPropertyDesc *message)
{
  assert(message->base.descriptor == &dm_game_object_ddf__component_property_desc__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t dm_game_object_ddf__component_property_desc__pack
                     (const DmGameObjectDDF__ComponentPropertyDesc *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &dm_game_object_ddf__component_property_desc__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t dm_game_object_ddf__component_property_desc__pack_to_buffer
                     (const DmGameObjectDDF__ComponentPropertyDesc *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &dm_game_object_ddf__component_property_desc__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
DmGameObjectDDF__ComponentPropertyDesc *
       dm_game_object_ddf__component_property_desc__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (DmGameObjectDDF__ComponentPropertyDesc *)
     protobuf_c_message_unpack (&dm_game_object_ddf__component_property_desc__descriptor,
                                allocator, len, data);
}
void   dm_game_object_ddf__component_property_desc__free_unpacked
                     (DmGameObjectDDF__ComponentPropertyDesc *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &dm_game_object_ddf__component_property_desc__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   dm_game_object_ddf__componen_type_desc__init
                     (DmGameObjectDDF__ComponenTypeDesc         *message)
{
  static const DmGameObjectDDF__ComponenTypeDesc init_value = DM_GAME_OBJECT_DDF__COMPONEN_TYPE_DESC__INIT;
  *message = init_value;
}
size_t dm_game_object_ddf__componen_type_desc__get_packed_size
                     (const DmGameObjectDDF__ComponenTypeDesc *message)
{
  assert(message->base.descriptor == &dm_game_object_ddf__componen_type_desc__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t dm_game_object_ddf__componen_type_desc__pack
                     (const DmGameObjectDDF__ComponenTypeDesc *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &dm_game_object_ddf__componen_type_desc__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t dm_game_object_ddf__componen_type_desc__pack_to_buffer
                     (const DmGameObjectDDF__ComponenTypeDesc *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &dm_game_object_ddf__componen_type_desc__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
DmGameObjectDDF__ComponenTypeDesc *
       dm_game_object_ddf__componen_type_desc__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (DmGameObjectDDF__ComponenTypeDesc *)
     protobuf_c_message_unpack (&dm_game_object_ddf__componen_type_desc__descriptor,
                                allocator, len, data);
}
void   dm_game_object_ddf__componen_type_desc__free_unpacked
                     (DmGameObjectDDF__ComponenTypeDesc *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &dm_game_object_ddf__componen_type_desc__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   dm_game_object_ddf__instance_desc__init
                     (DmGameObjectDDF__InstanceDesc         *message)
{
  static const DmGameObjectDDF__InstanceDesc init_value = DM_GAME_OBJECT_DDF__INSTANCE_DESC__INIT;
  *message = init_value;
}
size_t dm_game_object_ddf__instance_desc__get_packed_size
                     (const DmGameObjectDDF__InstanceDesc *message)
{
  assert(message->base.descriptor == &dm_game_object_ddf__instance_desc__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t dm_game_object_ddf__instance_desc__pack
                     (const DmGameObjectDDF__InstanceDesc *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &dm_game_object_ddf__instance_desc__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t dm_game_object_ddf__instance_desc__pack_to_buffer
                     (const DmGameObjectDDF__InstanceDesc *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &dm_game_object_ddf__instance_desc__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
DmGameObjectDDF__InstanceDesc *
       dm_game_object_ddf__instance_desc__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (DmGameObjectDDF__InstanceDesc *)
     protobuf_c_message_unpack (&dm_game_object_ddf__instance_desc__descriptor,
                                allocator, len, data);
}
void   dm_game_object_ddf__instance_desc__free_unpacked
                     (DmGameObjectDDF__InstanceDesc *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &dm_game_object_ddf__instance_desc__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   dm_game_object_ddf__embedded_instance_desc__init
                     (DmGameObjectDDF__EmbeddedInstanceDesc         *message)
{
  static const DmGameObjectDDF__EmbeddedInstanceDesc init_value = DM_GAME_OBJECT_DDF__EMBEDDED_INSTANCE_DESC__INIT;
  *message = init_value;
}
size_t dm_game_object_ddf__embedded_instance_desc__get_packed_size
                     (const DmGameObjectDDF__EmbeddedInstanceDesc *message)
{
  assert(message->base.descriptor == &dm_game_object_ddf__embedded_instance_desc__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t dm_game_object_ddf__embedded_instance_desc__pack
                     (const DmGameObjectDDF__EmbeddedInstanceDesc *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &dm_game_object_ddf__embedded_instance_desc__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t dm_game_object_ddf__embedded_instance_desc__pack_to_buffer
                     (const DmGameObjectDDF__EmbeddedInstanceDesc *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &dm_game_object_ddf__embedded_instance_desc__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
DmGameObjectDDF__EmbeddedInstanceDesc *
       dm_game_object_ddf__embedded_instance_desc__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (DmGameObjectDDF__EmbeddedInstanceDesc *)
     protobuf_c_message_unpack (&dm_game_object_ddf__embedded_instance_desc__descriptor,
                                allocator, len, data);
}
void   dm_game_object_ddf__embedded_instance_desc__free_unpacked
                     (DmGameObjectDDF__EmbeddedInstanceDesc *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &dm_game_object_ddf__embedded_instance_desc__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   dm_game_object_ddf__instance_property_desc__init
                     (DmGameObjectDDF__InstancePropertyDesc         *message)
{
  static const DmGameObjectDDF__InstancePropertyDesc init_value = DM_GAME_OBJECT_DDF__INSTANCE_PROPERTY_DESC__INIT;
  *message = init_value;
}
size_t dm_game_object_ddf__instance_property_desc__get_packed_size
                     (const DmGameObjectDDF__InstancePropertyDesc *message)
{
  assert(message->base.descriptor == &dm_game_object_ddf__instance_property_desc__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t dm_game_object_ddf__instance_property_desc__pack
                     (const DmGameObjectDDF__InstancePropertyDesc *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &dm_game_object_ddf__instance_property_desc__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t dm_game_object_ddf__instance_property_desc__pack_to_buffer
                     (const DmGameObjectDDF__InstancePropertyDesc *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &dm_game_object_ddf__instance_property_desc__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
DmGameObjectDDF__InstancePropertyDesc *
       dm_game_object_ddf__instance_property_desc__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (DmGameObjectDDF__InstancePropertyDesc *)
     protobuf_c_message_unpack (&dm_game_object_ddf__instance_property_desc__descriptor,
                                allocator, len, data);
}
void   dm_game_object_ddf__instance_property_desc__free_unpacked
                     (DmGameObjectDDF__InstancePropertyDesc *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &dm_game_object_ddf__instance_property_desc__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   dm_game_object_ddf__collection_instance_desc__init
                     (DmGameObjectDDF__CollectionInstanceDesc         *message)
{
  static const DmGameObjectDDF__CollectionInstanceDesc init_value = DM_GAME_OBJECT_DDF__COLLECTION_INSTANCE_DESC__INIT;
  *message = init_value;
}
size_t dm_game_object_ddf__collection_instance_desc__get_packed_size
                     (const DmGameObjectDDF__CollectionInstanceDesc *message)
{
  assert(message->base.descriptor == &dm_game_object_ddf__collection_instance_desc__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t dm_game_object_ddf__collection_instance_desc__pack
                     (const DmGameObjectDDF__CollectionInstanceDesc *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &dm_game_object_ddf__collection_instance_desc__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t dm_game_object_ddf__collection_instance_desc__pack_to_buffer
                     (const DmGameObjectDDF__CollectionInstanceDesc *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &dm_game_object_ddf__collection_instance_desc__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
DmGameObjectDDF__CollectionInstanceDesc *
       dm_game_object_ddf__collection_instance_desc__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (DmGameObjectDDF__CollectionInstanceDesc *)
     protobuf_c_message_unpack (&dm_game_object_ddf__collection_instance_desc__descriptor,
                                allocator, len, data);
}
void   dm_game_object_ddf__collection_instance_desc__free_unpacked
                     (DmGameObjectDDF__CollectionInstanceDesc *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &dm_game_object_ddf__collection_instance_desc__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   dm_game_object_ddf__collection_desc__init
                     (DmGameObjectDDF__CollectionDesc         *message)
{
  static const DmGameObjectDDF__CollectionDesc init_value = DM_GAME_OBJECT_DDF__COLLECTION_DESC__INIT;
  *message = init_value;
}
size_t dm_game_object_ddf__collection_desc__get_packed_size
                     (const DmGameObjectDDF__CollectionDesc *message)
{
  assert(message->base.descriptor == &dm_game_object_ddf__collection_desc__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t dm_game_object_ddf__collection_desc__pack
                     (const DmGameObjectDDF__CollectionDesc *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &dm_game_object_ddf__collection_desc__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t dm_game_object_ddf__collection_desc__pack_to_buffer
                     (const DmGameObjectDDF__CollectionDesc *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &dm_game_object_ddf__collection_desc__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
DmGameObjectDDF__CollectionDesc *
       dm_game_object_ddf__collection_desc__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (DmGameObjectDDF__CollectionDesc *)
     protobuf_c_message_unpack (&dm_game_object_ddf__collection_desc__descriptor,
                                allocator, len, data);
}
void   dm_game_object_ddf__collection_desc__free_unpacked
                     (DmGameObjectDDF__CollectionDesc *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &dm_game_object_ddf__collection_desc__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   dm_game_object_ddf__acquire_input_focus__init
                     (DmGameObjectDDF__AcquireInputFocus         *message)
{
  static const DmGameObjectDDF__AcquireInputFocus init_value = DM_GAME_OBJECT_DDF__ACQUIRE_INPUT_FOCUS__INIT;
  *message = init_value;
}
size_t dm_game_object_ddf__acquire_input_focus__get_packed_size
                     (const DmGameObjectDDF__AcquireInputFocus *message)
{
  assert(message->base.descriptor == &dm_game_object_ddf__acquire_input_focus__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t dm_game_object_ddf__acquire_input_focus__pack
                     (const DmGameObjectDDF__AcquireInputFocus *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &dm_game_object_ddf__acquire_input_focus__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t dm_game_object_ddf__acquire_input_focus__pack_to_buffer
                     (const DmGameObjectDDF__AcquireInputFocus *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &dm_game_object_ddf__acquire_input_focus__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
DmGameObjectDDF__AcquireInputFocus *
       dm_game_object_ddf__acquire_input_focus__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (DmGameObjectDDF__AcquireInputFocus *)
     protobuf_c_message_unpack (&dm_game_object_ddf__acquire_input_focus__descriptor,
                                allocator, len, data);
}
void   dm_game_object_ddf__acquire_input_focus__free_unpacked
                     (DmGameObjectDDF__AcquireInputFocus *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &dm_game_object_ddf__acquire_input_focus__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   dm_game_object_ddf__release_input_focus__init
                     (DmGameObjectDDF__ReleaseInputFocus         *message)
{
  static const DmGameObjectDDF__ReleaseInputFocus init_value = DM_GAME_OBJECT_DDF__RELEASE_INPUT_FOCUS__INIT;
  *message = init_value;
}
size_t dm_game_object_ddf__release_input_focus__get_packed_size
                     (const DmGameObjectDDF__ReleaseInputFocus *message)
{
  assert(message->base.descriptor == &dm_game_object_ddf__release_input_focus__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t dm_game_object_ddf__release_input_focus__pack
                     (const DmGameObjectDDF__ReleaseInputFocus *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &dm_game_object_ddf__release_input_focus__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t dm_game_object_ddf__release_input_focus__pack_to_buffer
                     (const DmGameObjectDDF__ReleaseInputFocus *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &dm_game_object_ddf__release_input_focus__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
DmGameObjectDDF__ReleaseInputFocus *
       dm_game_object_ddf__release_input_focus__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (DmGameObjectDDF__ReleaseInputFocus *)
     protobuf_c_message_unpack (&dm_game_object_ddf__release_input_focus__descriptor,
                                allocator, len, data);
}
void   dm_game_object_ddf__release_input_focus__free_unpacked
                     (DmGameObjectDDF__ReleaseInputFocus *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &dm_game_object_ddf__release_input_focus__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   dm_game_object_ddf__request_transform__init
                     (DmGameObjectDDF__RequestTransform         *message)
{
  static const DmGameObjectDDF__RequestTransform init_value = DM_GAME_OBJECT_DDF__REQUEST_TRANSFORM__INIT;
  *message = init_value;
}
size_t dm_game_object_ddf__request_transform__get_packed_size
                     (const DmGameObjectDDF__RequestTransform *message)
{
  assert(message->base.descriptor == &dm_game_object_ddf__request_transform__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t dm_game_object_ddf__request_transform__pack
                     (const DmGameObjectDDF__RequestTransform *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &dm_game_object_ddf__request_transform__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t dm_game_object_ddf__request_transform__pack_to_buffer
                     (const DmGameObjectDDF__RequestTransform *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &dm_game_object_ddf__request_transform__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
DmGameObjectDDF__RequestTransform *
       dm_game_object_ddf__request_transform__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (DmGameObjectDDF__RequestTransform *)
     protobuf_c_message_unpack (&dm_game_object_ddf__request_transform__descriptor,
                                allocator, len, data);
}
void   dm_game_object_ddf__request_transform__free_unpacked
                     (DmGameObjectDDF__RequestTransform *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &dm_game_object_ddf__request_transform__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   dm_game_object_ddf__transform_response__init
                     (DmGameObjectDDF__TransformResponse         *message)
{
  static const DmGameObjectDDF__TransformResponse init_value = DM_GAME_OBJECT_DDF__TRANSFORM_RESPONSE__INIT;
  *message = init_value;
}
size_t dm_game_object_ddf__transform_response__get_packed_size
                     (const DmGameObjectDDF__TransformResponse *message)
{
  assert(message->base.descriptor == &dm_game_object_ddf__transform_response__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t dm_game_object_ddf__transform_response__pack
                     (const DmGameObjectDDF__TransformResponse *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &dm_game_object_ddf__transform_response__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t dm_game_object_ddf__transform_response__pack_to_buffer
                     (const DmGameObjectDDF__TransformResponse *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &dm_game_object_ddf__transform_response__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
DmGameObjectDDF__TransformResponse *
       dm_game_object_ddf__transform_response__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (DmGameObjectDDF__TransformResponse *)
     protobuf_c_message_unpack (&dm_game_object_ddf__transform_response__descriptor,
                                allocator, len, data);
}
void   dm_game_object_ddf__transform_response__free_unpacked
                     (DmGameObjectDDF__TransformResponse *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &dm_game_object_ddf__transform_response__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   dm_game_object_ddf__set_parent__init
                     (DmGameObjectDDF__SetParent         *message)
{
  static const DmGameObjectDDF__SetParent init_value = DM_GAME_OBJECT_DDF__SET_PARENT__INIT;
  *message = init_value;
}
size_t dm_game_object_ddf__set_parent__get_packed_size
                     (const DmGameObjectDDF__SetParent *message)
{
  assert(message->base.descriptor == &dm_game_object_ddf__set_parent__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t dm_game_object_ddf__set_parent__pack
                     (const DmGameObjectDDF__SetParent *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &dm_game_object_ddf__set_parent__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t dm_game_object_ddf__set_parent__pack_to_buffer
                     (const DmGameObjectDDF__SetParent *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &dm_game_object_ddf__set_parent__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
DmGameObjectDDF__SetParent *
       dm_game_object_ddf__set_parent__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (DmGameObjectDDF__SetParent *)
     protobuf_c_message_unpack (&dm_game_object_ddf__set_parent__descriptor,
                                allocator, len, data);
}
void   dm_game_object_ddf__set_parent__free_unpacked
                     (DmGameObjectDDF__SetParent *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &dm_game_object_ddf__set_parent__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   dm_game_object_ddf__enable__init
                     (DmGameObjectDDF__Enable         *message)
{
  static const DmGameObjectDDF__Enable init_value = DM_GAME_OBJECT_DDF__ENABLE__INIT;
  *message = init_value;
}
size_t dm_game_object_ddf__enable__get_packed_size
                     (const DmGameObjectDDF__Enable *message)
{
  assert(message->base.descriptor == &dm_game_object_ddf__enable__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t dm_game_object_ddf__enable__pack
                     (const DmGameObjectDDF__Enable *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &dm_game_object_ddf__enable__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t dm_game_object_ddf__enable__pack_to_buffer
                     (const DmGameObjectDDF__Enable *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &dm_game_object_ddf__enable__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
DmGameObjectDDF__Enable *
       dm_game_object_ddf__enable__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (DmGameObjectDDF__Enable *)
     protobuf_c_message_unpack (&dm_game_object_ddf__enable__descriptor,
                                allocator, len, data);
}
void   dm_game_object_ddf__enable__free_unpacked
                     (DmGameObjectDDF__Enable *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &dm_game_object_ddf__enable__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   dm_game_object_ddf__disable__init
                     (DmGameObjectDDF__Disable         *message)
{
  static const DmGameObjectDDF__Disable init_value = DM_GAME_OBJECT_DDF__DISABLE__INIT;
  *message = init_value;
}
size_t dm_game_object_ddf__disable__get_packed_size
                     (const DmGameObjectDDF__Disable *message)
{
  assert(message->base.descriptor == &dm_game_object_ddf__disable__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t dm_game_object_ddf__disable__pack
                     (const DmGameObjectDDF__Disable *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &dm_game_object_ddf__disable__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t dm_game_object_ddf__disable__pack_to_buffer
                     (const DmGameObjectDDF__Disable *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &dm_game_object_ddf__disable__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
DmGameObjectDDF__Disable *
       dm_game_object_ddf__disable__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (DmGameObjectDDF__Disable *)
     protobuf_c_message_unpack (&dm_game_object_ddf__disable__descriptor,
                                allocator, len, data);
}
void   dm_game_object_ddf__disable__free_unpacked
                     (DmGameObjectDDF__Disable *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &dm_game_object_ddf__disable__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   dm_game_object_ddf__script_message__init
                     (DmGameObjectDDF__ScriptMessage         *message)
{
  static const DmGameObjectDDF__ScriptMessage init_value = DM_GAME_OBJECT_DDF__SCRIPT_MESSAGE__INIT;
  *message = init_value;
}
size_t dm_game_object_ddf__script_message__get_packed_size
                     (const DmGameObjectDDF__ScriptMessage *message)
{
  assert(message->base.descriptor == &dm_game_object_ddf__script_message__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t dm_game_object_ddf__script_message__pack
                     (const DmGameObjectDDF__ScriptMessage *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &dm_game_object_ddf__script_message__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t dm_game_object_ddf__script_message__pack_to_buffer
                     (const DmGameObjectDDF__ScriptMessage *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &dm_game_object_ddf__script_message__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
DmGameObjectDDF__ScriptMessage *
       dm_game_object_ddf__script_message__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (DmGameObjectDDF__ScriptMessage *)
     protobuf_c_message_unpack (&dm_game_object_ddf__script_message__descriptor,
                                allocator, len, data);
}
void   dm_game_object_ddf__script_message__free_unpacked
                     (DmGameObjectDDF__ScriptMessage *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &dm_game_object_ddf__script_message__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor dm_game_object_ddf__property_desc__field_descriptors[3] =
{
  {
    "id",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(DmGameObjectDDF__PropertyDesc, id),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "value",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(DmGameObjectDDF__PropertyDesc, value),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "type",
    3,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(DmGameObjectDDF__PropertyDesc, type),
    &dm_game_object_ddf__property_type__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned dm_game_object_ddf__property_desc__field_indices_by_name[] = {
  0,   /* field[0] = id */
  2,   /* field[2] = type */
  1,   /* field[1] = value */
};
static const ProtobufCIntRange dm_game_object_ddf__property_desc__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor dm_game_object_ddf__property_desc__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "dmGameObjectDDF.PropertyDesc",
  "PropertyDesc",
  "DmGameObjectDDF__PropertyDesc",
  "dmGameObjectDDF",
  sizeof(DmGameObjectDDF__PropertyDesc),
  3,
  dm_game_object_ddf__property_desc__field_descriptors,
  dm_game_object_ddf__property_desc__field_indices_by_name,
  1,  dm_game_object_ddf__property_desc__number_ranges,
  (ProtobufCMessageInit) dm_game_object_ddf__property_desc__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor dm_game_object_ddf__component_desc__field_descriptors[7] =
{
  {
    "id",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(DmGameObjectDDF__ComponentDesc, id),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "component",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(DmGameObjectDDF__ComponentDesc, component),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "position",
    3,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(DmGameObjectDDF__ComponentDesc, position),
    &dm_math__point3__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "rotation",
    4,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(DmGameObjectDDF__ComponentDesc, rotation),
    &dm_math__quat__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "properties",
    5,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(DmGameObjectDDF__ComponentDesc, n_properties),
    offsetof(DmGameObjectDDF__ComponentDesc, properties),
    &dm_game_object_ddf__property_desc__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "property_decls",
    6,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(DmGameObjectDDF__ComponentDesc, property_decls),
    &dm_properties_ddf__property_declarations__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "scale",
    7,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(DmGameObjectDDF__ComponentDesc, scale),
    &dm_math__vector3__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned dm_game_object_ddf__component_desc__field_indices_by_name[] = {
  1,   /* field[1] = component */
  0,   /* field[0] = id */
  2,   /* field[2] = position */
  4,   /* field[4] = properties */
  5,   /* field[5] = property_decls */
  3,   /* field[3] = rotation */
  6,   /* field[6] = scale */
};
static const ProtobufCIntRange dm_game_object_ddf__component_desc__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 7 }
};
const ProtobufCMessageDescriptor dm_game_object_ddf__component_desc__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "dmGameObjectDDF.ComponentDesc",
  "ComponentDesc",
  "DmGameObjectDDF__ComponentDesc",
  "dmGameObjectDDF",
  sizeof(DmGameObjectDDF__ComponentDesc),
  7,
  dm_game_object_ddf__component_desc__field_descriptors,
  dm_game_object_ddf__component_desc__field_indices_by_name,
  1,  dm_game_object_ddf__component_desc__number_ranges,
  (ProtobufCMessageInit) dm_game_object_ddf__component_desc__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor dm_game_object_ddf__embedded_component_desc__field_descriptors[6] =
{
  {
    "id",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(DmGameObjectDDF__EmbeddedComponentDesc, id),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "type",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(DmGameObjectDDF__EmbeddedComponentDesc, type),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "data",
    3,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(DmGameObjectDDF__EmbeddedComponentDesc, data),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "position",
    4,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(DmGameObjectDDF__EmbeddedComponentDesc, position),
    &dm_math__point3__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "rotation",
    5,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(DmGameObjectDDF__EmbeddedComponentDesc, rotation),
    &dm_math__quat__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "scale",
    6,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(DmGameObjectDDF__EmbeddedComponentDesc, scale),
    &dm_math__vector3__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned dm_game_object_ddf__embedded_component_desc__field_indices_by_name[] = {
  2,   /* field[2] = data */
  0,   /* field[0] = id */
  3,   /* field[3] = position */
  4,   /* field[4] = rotation */
  5,   /* field[5] = scale */
  1,   /* field[1] = type */
};
static const ProtobufCIntRange dm_game_object_ddf__embedded_component_desc__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 6 }
};
const ProtobufCMessageDescriptor dm_game_object_ddf__embedded_component_desc__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "dmGameObjectDDF.EmbeddedComponentDesc",
  "EmbeddedComponentDesc",
  "DmGameObjectDDF__EmbeddedComponentDesc",
  "dmGameObjectDDF",
  sizeof(DmGameObjectDDF__EmbeddedComponentDesc),
  6,
  dm_game_object_ddf__embedded_component_desc__field_descriptors,
  dm_game_object_ddf__embedded_component_desc__field_indices_by_name,
  1,  dm_game_object_ddf__embedded_component_desc__number_ranges,
  (ProtobufCMessageInit) dm_game_object_ddf__embedded_component_desc__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor dm_game_object_ddf__prototype_desc__field_descriptors[3] =
{
  {
    "components",
    1,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(DmGameObjectDDF__PrototypeDesc, n_components),
    offsetof(DmGameObjectDDF__PrototypeDesc, components),
    &dm_game_object_ddf__component_desc__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "embedded_components",
    2,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(DmGameObjectDDF__PrototypeDesc, n_embedded_components),
    offsetof(DmGameObjectDDF__PrototypeDesc, embedded_components),
    &dm_game_object_ddf__embedded_component_desc__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "property_resources",
    3,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_STRING,
    offsetof(DmGameObjectDDF__PrototypeDesc, n_property_resources),
    offsetof(DmGameObjectDDF__PrototypeDesc, property_resources),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned dm_game_object_ddf__prototype_desc__field_indices_by_name[] = {
  0,   /* field[0] = components */
  1,   /* field[1] = embedded_components */
  2,   /* field[2] = property_resources */
};
static const ProtobufCIntRange dm_game_object_ddf__prototype_desc__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor dm_game_object_ddf__prototype_desc__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "dmGameObjectDDF.PrototypeDesc",
  "PrototypeDesc",
  "DmGameObjectDDF__PrototypeDesc",
  "dmGameObjectDDF",
  sizeof(DmGameObjectDDF__PrototypeDesc),
  3,
  dm_game_object_ddf__prototype_desc__field_descriptors,
  dm_game_object_ddf__prototype_desc__field_indices_by_name,
  1,  dm_game_object_ddf__prototype_desc__number_ranges,
  (ProtobufCMessageInit) dm_game_object_ddf__prototype_desc__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor dm_game_object_ddf__component_property_desc__field_descriptors[3] =
{
  {
    "id",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(DmGameObjectDDF__ComponentPropertyDesc, id),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "properties",
    2,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(DmGameObjectDDF__ComponentPropertyDesc, n_properties),
    offsetof(DmGameObjectDDF__ComponentPropertyDesc, properties),
    &dm_game_object_ddf__property_desc__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "property_decls",
    3,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(DmGameObjectDDF__ComponentPropertyDesc, property_decls),
    &dm_properties_ddf__property_declarations__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned dm_game_object_ddf__component_property_desc__field_indices_by_name[] = {
  0,   /* field[0] = id */
  1,   /* field[1] = properties */
  2,   /* field[2] = property_decls */
};
static const ProtobufCIntRange dm_game_object_ddf__component_property_desc__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor dm_game_object_ddf__component_property_desc__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "dmGameObjectDDF.ComponentPropertyDesc",
  "ComponentPropertyDesc",
  "DmGameObjectDDF__ComponentPropertyDesc",
  "dmGameObjectDDF",
  sizeof(DmGameObjectDDF__ComponentPropertyDesc),
  3,
  dm_game_object_ddf__component_property_desc__field_descriptors,
  dm_game_object_ddf__component_property_desc__field_indices_by_name,
  1,  dm_game_object_ddf__component_property_desc__number_ranges,
  (ProtobufCMessageInit) dm_game_object_ddf__component_property_desc__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor dm_game_object_ddf__componen_type_desc__field_descriptors[2] =
{
  {
    "name_hash",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    offsetof(DmGameObjectDDF__ComponenTypeDesc, name_hash),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "max_count",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(DmGameObjectDDF__ComponenTypeDesc, max_count),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned dm_game_object_ddf__componen_type_desc__field_indices_by_name[] = {
  1,   /* field[1] = max_count */
  0,   /* field[0] = name_hash */
};
static const ProtobufCIntRange dm_game_object_ddf__componen_type_desc__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor dm_game_object_ddf__componen_type_desc__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "dmGameObjectDDF.ComponenTypeDesc",
  "ComponenTypeDesc",
  "DmGameObjectDDF__ComponenTypeDesc",
  "dmGameObjectDDF",
  sizeof(DmGameObjectDDF__ComponenTypeDesc),
  2,
  dm_game_object_ddf__componen_type_desc__field_descriptors,
  dm_game_object_ddf__componen_type_desc__field_indices_by_name,
  1,  dm_game_object_ddf__componen_type_desc__number_ranges,
  (ProtobufCMessageInit) dm_game_object_ddf__componen_type_desc__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const float dm_game_object_ddf__instance_desc__scale__default_value = 1;
static const ProtobufCFieldDescriptor dm_game_object_ddf__instance_desc__field_descriptors[8] =
{
  {
    "id",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(DmGameObjectDDF__InstanceDesc, id),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "prototype",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(DmGameObjectDDF__InstanceDesc, prototype),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "children",
    3,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_STRING,
    offsetof(DmGameObjectDDF__InstanceDesc, n_children),
    offsetof(DmGameObjectDDF__InstanceDesc, children),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "position",
    4,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(DmGameObjectDDF__InstanceDesc, position),
    &dm_math__point3__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "rotation",
    5,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(DmGameObjectDDF__InstanceDesc, rotation),
    &dm_math__quat__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "component_properties",
    6,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(DmGameObjectDDF__InstanceDesc, n_component_properties),
    offsetof(DmGameObjectDDF__InstanceDesc, component_properties),
    &dm_game_object_ddf__component_property_desc__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "scale",
    7,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_FLOAT,
    offsetof(DmGameObjectDDF__InstanceDesc, has_scale),
    offsetof(DmGameObjectDDF__InstanceDesc, scale),
    NULL,
    &dm_game_object_ddf__instance_desc__scale__default_value,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "scale3",
    8,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(DmGameObjectDDF__InstanceDesc, scale3),
    &dm_math__vector3__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned dm_game_object_ddf__instance_desc__field_indices_by_name[] = {
  2,   /* field[2] = children */
  5,   /* field[5] = component_properties */
  0,   /* field[0] = id */
  3,   /* field[3] = position */
  1,   /* field[1] = prototype */
  4,   /* field[4] = rotation */
  6,   /* field[6] = scale */
  7,   /* field[7] = scale3 */
};
static const ProtobufCIntRange dm_game_object_ddf__instance_desc__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 8 }
};
const ProtobufCMessageDescriptor dm_game_object_ddf__instance_desc__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "dmGameObjectDDF.InstanceDesc",
  "InstanceDesc",
  "DmGameObjectDDF__InstanceDesc",
  "dmGameObjectDDF",
  sizeof(DmGameObjectDDF__InstanceDesc),
  8,
  dm_game_object_ddf__instance_desc__field_descriptors,
  dm_game_object_ddf__instance_desc__field_indices_by_name,
  1,  dm_game_object_ddf__instance_desc__number_ranges,
  (ProtobufCMessageInit) dm_game_object_ddf__instance_desc__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const float dm_game_object_ddf__embedded_instance_desc__scale__default_value = 1;
static const ProtobufCFieldDescriptor dm_game_object_ddf__embedded_instance_desc__field_descriptors[8] =
{
  {
    "id",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(DmGameObjectDDF__EmbeddedInstanceDesc, id),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "children",
    2,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_STRING,
    offsetof(DmGameObjectDDF__EmbeddedInstanceDesc, n_children),
    offsetof(DmGameObjectDDF__EmbeddedInstanceDesc, children),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "data",
    3,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(DmGameObjectDDF__EmbeddedInstanceDesc, data),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "position",
    4,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(DmGameObjectDDF__EmbeddedInstanceDesc, position),
    &dm_math__point3__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "rotation",
    5,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(DmGameObjectDDF__EmbeddedInstanceDesc, rotation),
    &dm_math__quat__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "component_properties",
    6,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(DmGameObjectDDF__EmbeddedInstanceDesc, n_component_properties),
    offsetof(DmGameObjectDDF__EmbeddedInstanceDesc, component_properties),
    &dm_game_object_ddf__component_property_desc__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "scale",
    7,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_FLOAT,
    offsetof(DmGameObjectDDF__EmbeddedInstanceDesc, has_scale),
    offsetof(DmGameObjectDDF__EmbeddedInstanceDesc, scale),
    NULL,
    &dm_game_object_ddf__embedded_instance_desc__scale__default_value,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "scale3",
    8,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(DmGameObjectDDF__EmbeddedInstanceDesc, scale3),
    &dm_math__vector3__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned dm_game_object_ddf__embedded_instance_desc__field_indices_by_name[] = {
  1,   /* field[1] = children */
  5,   /* field[5] = component_properties */
  2,   /* field[2] = data */
  0,   /* field[0] = id */
  3,   /* field[3] = position */
  4,   /* field[4] = rotation */
  6,   /* field[6] = scale */
  7,   /* field[7] = scale3 */
};
static const ProtobufCIntRange dm_game_object_ddf__embedded_instance_desc__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 8 }
};
const ProtobufCMessageDescriptor dm_game_object_ddf__embedded_instance_desc__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "dmGameObjectDDF.EmbeddedInstanceDesc",
  "EmbeddedInstanceDesc",
  "DmGameObjectDDF__EmbeddedInstanceDesc",
  "dmGameObjectDDF",
  sizeof(DmGameObjectDDF__EmbeddedInstanceDesc),
  8,
  dm_game_object_ddf__embedded_instance_desc__field_descriptors,
  dm_game_object_ddf__embedded_instance_desc__field_indices_by_name,
  1,  dm_game_object_ddf__embedded_instance_desc__number_ranges,
  (ProtobufCMessageInit) dm_game_object_ddf__embedded_instance_desc__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor dm_game_object_ddf__instance_property_desc__field_descriptors[2] =
{
  {
    "id",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(DmGameObjectDDF__InstancePropertyDesc, id),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "properties",
    2,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(DmGameObjectDDF__InstancePropertyDesc, n_properties),
    offsetof(DmGameObjectDDF__InstancePropertyDesc, properties),
    &dm_game_object_ddf__component_property_desc__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned dm_game_object_ddf__instance_property_desc__field_indices_by_name[] = {
  0,   /* field[0] = id */
  1,   /* field[1] = properties */
};
static const ProtobufCIntRange dm_game_object_ddf__instance_property_desc__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor dm_game_object_ddf__instance_property_desc__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "dmGameObjectDDF.InstancePropertyDesc",
  "InstancePropertyDesc",
  "DmGameObjectDDF__InstancePropertyDesc",
  "dmGameObjectDDF",
  sizeof(DmGameObjectDDF__InstancePropertyDesc),
  2,
  dm_game_object_ddf__instance_property_desc__field_descriptors,
  dm_game_object_ddf__instance_property_desc__field_indices_by_name,
  1,  dm_game_object_ddf__instance_property_desc__number_ranges,
  (ProtobufCMessageInit) dm_game_object_ddf__instance_property_desc__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const float dm_game_object_ddf__collection_instance_desc__scale__default_value = 1;
static const ProtobufCFieldDescriptor dm_game_object_ddf__collection_instance_desc__field_descriptors[7] =
{
  {
    "id",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(DmGameObjectDDF__CollectionInstanceDesc, id),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "collection",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(DmGameObjectDDF__CollectionInstanceDesc, collection),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "position",
    3,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(DmGameObjectDDF__CollectionInstanceDesc, position),
    &dm_math__point3__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "rotation",
    4,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(DmGameObjectDDF__CollectionInstanceDesc, rotation),
    &dm_math__quat__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "scale",
    5,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_FLOAT,
    offsetof(DmGameObjectDDF__CollectionInstanceDesc, has_scale),
    offsetof(DmGameObjectDDF__CollectionInstanceDesc, scale),
    NULL,
    &dm_game_object_ddf__collection_instance_desc__scale__default_value,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "instance_properties",
    6,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(DmGameObjectDDF__CollectionInstanceDesc, n_instance_properties),
    offsetof(DmGameObjectDDF__CollectionInstanceDesc, instance_properties),
    &dm_game_object_ddf__instance_property_desc__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "scale3",
    7,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(DmGameObjectDDF__CollectionInstanceDesc, scale3),
    &dm_math__vector3__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned dm_game_object_ddf__collection_instance_desc__field_indices_by_name[] = {
  1,   /* field[1] = collection */
  0,   /* field[0] = id */
  5,   /* field[5] = instance_properties */
  2,   /* field[2] = position */
  3,   /* field[3] = rotation */
  4,   /* field[4] = scale */
  6,   /* field[6] = scale3 */
};
static const ProtobufCIntRange dm_game_object_ddf__collection_instance_desc__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 7 }
};
const ProtobufCMessageDescriptor dm_game_object_ddf__collection_instance_desc__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "dmGameObjectDDF.CollectionInstanceDesc",
  "CollectionInstanceDesc",
  "DmGameObjectDDF__CollectionInstanceDesc",
  "dmGameObjectDDF",
  sizeof(DmGameObjectDDF__CollectionInstanceDesc),
  7,
  dm_game_object_ddf__collection_instance_desc__field_descriptors,
  dm_game_object_ddf__collection_instance_desc__field_indices_by_name,
  1,  dm_game_object_ddf__collection_instance_desc__number_ranges,
  (ProtobufCMessageInit) dm_game_object_ddf__collection_instance_desc__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const uint32_t dm_game_object_ddf__collection_desc__scale_along_z__default_value = 0u;
static const ProtobufCFieldDescriptor dm_game_object_ddf__collection_desc__field_descriptors[7] =
{
  {
    "name",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(DmGameObjectDDF__CollectionDesc, name),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "instances",
    2,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(DmGameObjectDDF__CollectionDesc, n_instances),
    offsetof(DmGameObjectDDF__CollectionDesc, instances),
    &dm_game_object_ddf__instance_desc__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "collection_instances",
    3,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(DmGameObjectDDF__CollectionDesc, n_collection_instances),
    offsetof(DmGameObjectDDF__CollectionDesc, collection_instances),
    &dm_game_object_ddf__collection_instance_desc__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "scale_along_z",
    4,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(DmGameObjectDDF__CollectionDesc, has_scale_along_z),
    offsetof(DmGameObjectDDF__CollectionDesc, scale_along_z),
    NULL,
    &dm_game_object_ddf__collection_desc__scale_along_z__default_value,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "embedded_instances",
    5,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(DmGameObjectDDF__CollectionDesc, n_embedded_instances),
    offsetof(DmGameObjectDDF__CollectionDesc, embedded_instances),
    &dm_game_object_ddf__embedded_instance_desc__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "property_resources",
    6,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_STRING,
    offsetof(DmGameObjectDDF__CollectionDesc, n_property_resources),
    offsetof(DmGameObjectDDF__CollectionDesc, property_resources),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "component_types",
    7,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(DmGameObjectDDF__CollectionDesc, n_component_types),
    offsetof(DmGameObjectDDF__CollectionDesc, component_types),
    &dm_game_object_ddf__componen_type_desc__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned dm_game_object_ddf__collection_desc__field_indices_by_name[] = {
  2,   /* field[2] = collection_instances */
  6,   /* field[6] = component_types */
  4,   /* field[4] = embedded_instances */
  1,   /* field[1] = instances */
  0,   /* field[0] = name */
  5,   /* field[5] = property_resources */
  3,   /* field[3] = scale_along_z */
};
static const ProtobufCIntRange dm_game_object_ddf__collection_desc__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 7 }
};
const ProtobufCMessageDescriptor dm_game_object_ddf__collection_desc__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "dmGameObjectDDF.CollectionDesc",
  "CollectionDesc",
  "DmGameObjectDDF__CollectionDesc",
  "dmGameObjectDDF",
  sizeof(DmGameObjectDDF__CollectionDesc),
  7,
  dm_game_object_ddf__collection_desc__field_descriptors,
  dm_game_object_ddf__collection_desc__field_indices_by_name,
  1,  dm_game_object_ddf__collection_desc__number_ranges,
  (ProtobufCMessageInit) dm_game_object_ddf__collection_desc__init,
  NULL,NULL,NULL    /* reserved[123] */
};
#define dm_game_object_ddf__acquire_input_focus__field_descriptors NULL
#define dm_game_object_ddf__acquire_input_focus__field_indices_by_name NULL
#define dm_game_object_ddf__acquire_input_focus__number_ranges NULL
const ProtobufCMessageDescriptor dm_game_object_ddf__acquire_input_focus__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "dmGameObjectDDF.AcquireInputFocus",
  "AcquireInputFocus",
  "DmGameObjectDDF__AcquireInputFocus",
  "dmGameObjectDDF",
  sizeof(DmGameObjectDDF__AcquireInputFocus),
  0,
  dm_game_object_ddf__acquire_input_focus__field_descriptors,
  dm_game_object_ddf__acquire_input_focus__field_indices_by_name,
  0,  dm_game_object_ddf__acquire_input_focus__number_ranges,
  (ProtobufCMessageInit) dm_game_object_ddf__acquire_input_focus__init,
  NULL,NULL,NULL    /* reserved[123] */
};
#define dm_game_object_ddf__release_input_focus__field_descriptors NULL
#define dm_game_object_ddf__release_input_focus__field_indices_by_name NULL
#define dm_game_object_ddf__release_input_focus__number_ranges NULL
const ProtobufCMessageDescriptor dm_game_object_ddf__release_input_focus__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "dmGameObjectDDF.ReleaseInputFocus",
  "ReleaseInputFocus",
  "DmGameObjectDDF__ReleaseInputFocus",
  "dmGameObjectDDF",
  sizeof(DmGameObjectDDF__ReleaseInputFocus),
  0,
  dm_game_object_ddf__release_input_focus__field_descriptors,
  dm_game_object_ddf__release_input_focus__field_indices_by_name,
  0,  dm_game_object_ddf__release_input_focus__number_ranges,
  (ProtobufCMessageInit) dm_game_object_ddf__release_input_focus__init,
  NULL,NULL,NULL    /* reserved[123] */
};
#define dm_game_object_ddf__request_transform__field_descriptors NULL
#define dm_game_object_ddf__request_transform__field_indices_by_name NULL
#define dm_game_object_ddf__request_transform__number_ranges NULL
const ProtobufCMessageDescriptor dm_game_object_ddf__request_transform__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "dmGameObjectDDF.RequestTransform",
  "RequestTransform",
  "DmGameObjectDDF__RequestTransform",
  "dmGameObjectDDF",
  sizeof(DmGameObjectDDF__RequestTransform),
  0,
  dm_game_object_ddf__request_transform__field_descriptors,
  dm_game_object_ddf__request_transform__field_indices_by_name,
  0,  dm_game_object_ddf__request_transform__number_ranges,
  (ProtobufCMessageInit) dm_game_object_ddf__request_transform__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const float dm_game_object_ddf__transform_response__scale__default_value = 1;
static const float dm_game_object_ddf__transform_response__world_scale__default_value = 1;
static const ProtobufCFieldDescriptor dm_game_object_ddf__transform_response__field_descriptors[8] =
{
  {
    "position",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(DmGameObjectDDF__TransformResponse, position),
    &dm_math__point3__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "rotation",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(DmGameObjectDDF__TransformResponse, rotation),
    &dm_math__quat__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "world_position",
    3,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(DmGameObjectDDF__TransformResponse, world_position),
    &dm_math__point3__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "world_rotation",
    4,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(DmGameObjectDDF__TransformResponse, world_rotation),
    &dm_math__quat__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "scale",
    5,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_FLOAT,
    offsetof(DmGameObjectDDF__TransformResponse, has_scale),
    offsetof(DmGameObjectDDF__TransformResponse, scale),
    NULL,
    &dm_game_object_ddf__transform_response__scale__default_value,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "world_scale",
    6,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_FLOAT,
    offsetof(DmGameObjectDDF__TransformResponse, has_world_scale),
    offsetof(DmGameObjectDDF__TransformResponse, world_scale),
    NULL,
    &dm_game_object_ddf__transform_response__world_scale__default_value,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "scale3",
    7,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(DmGameObjectDDF__TransformResponse, scale3),
    &dm_math__vector3__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "world_scale3",
    8,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(DmGameObjectDDF__TransformResponse, world_scale3),
    &dm_math__vector3__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned dm_game_object_ddf__transform_response__field_indices_by_name[] = {
  0,   /* field[0] = position */
  1,   /* field[1] = rotation */
  4,   /* field[4] = scale */
  6,   /* field[6] = scale3 */
  2,   /* field[2] = world_position */
  3,   /* field[3] = world_rotation */
  5,   /* field[5] = world_scale */
  7,   /* field[7] = world_scale3 */
};
static const ProtobufCIntRange dm_game_object_ddf__transform_response__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 8 }
};
const ProtobufCMessageDescriptor dm_game_object_ddf__transform_response__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "dmGameObjectDDF.TransformResponse",
  "TransformResponse",
  "DmGameObjectDDF__TransformResponse",
  "dmGameObjectDDF",
  sizeof(DmGameObjectDDF__TransformResponse),
  8,
  dm_game_object_ddf__transform_response__field_descriptors,
  dm_game_object_ddf__transform_response__field_indices_by_name,
  1,  dm_game_object_ddf__transform_response__number_ranges,
  (ProtobufCMessageInit) dm_game_object_ddf__transform_response__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const uint64_t dm_game_object_ddf__set_parent__parent_id__default_value = 0ull;
static const uint32_t dm_game_object_ddf__set_parent__keep_world_transform__default_value = 1u;
static const ProtobufCFieldDescriptor dm_game_object_ddf__set_parent__field_descriptors[2] =
{
  {
    "parent_id",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT64,
    offsetof(DmGameObjectDDF__SetParent, has_parent_id),
    offsetof(DmGameObjectDDF__SetParent, parent_id),
    NULL,
    &dm_game_object_ddf__set_parent__parent_id__default_value,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "keep_world_transform",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(DmGameObjectDDF__SetParent, has_keep_world_transform),
    offsetof(DmGameObjectDDF__SetParent, keep_world_transform),
    NULL,
    &dm_game_object_ddf__set_parent__keep_world_transform__default_value,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned dm_game_object_ddf__set_parent__field_indices_by_name[] = {
  1,   /* field[1] = keep_world_transform */
  0,   /* field[0] = parent_id */
};
static const ProtobufCIntRange dm_game_object_ddf__set_parent__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor dm_game_object_ddf__set_parent__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "dmGameObjectDDF.SetParent",
  "SetParent",
  "DmGameObjectDDF__SetParent",
  "dmGameObjectDDF",
  sizeof(DmGameObjectDDF__SetParent),
  2,
  dm_game_object_ddf__set_parent__field_descriptors,
  dm_game_object_ddf__set_parent__field_indices_by_name,
  1,  dm_game_object_ddf__set_parent__number_ranges,
  (ProtobufCMessageInit) dm_game_object_ddf__set_parent__init,
  NULL,NULL,NULL    /* reserved[123] */
};
#define dm_game_object_ddf__enable__field_descriptors NULL
#define dm_game_object_ddf__enable__field_indices_by_name NULL
#define dm_game_object_ddf__enable__number_ranges NULL
const ProtobufCMessageDescriptor dm_game_object_ddf__enable__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "dmGameObjectDDF.Enable",
  "Enable",
  "DmGameObjectDDF__Enable",
  "dmGameObjectDDF",
  sizeof(DmGameObjectDDF__Enable),
  0,
  dm_game_object_ddf__enable__field_descriptors,
  dm_game_object_ddf__enable__field_indices_by_name,
  0,  dm_game_object_ddf__enable__number_ranges,
  (ProtobufCMessageInit) dm_game_object_ddf__enable__init,
  NULL,NULL,NULL    /* reserved[123] */
};
#define dm_game_object_ddf__disable__field_descriptors NULL
#define dm_game_object_ddf__disable__field_indices_by_name NULL
#define dm_game_object_ddf__disable__number_ranges NULL
const ProtobufCMessageDescriptor dm_game_object_ddf__disable__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "dmGameObjectDDF.Disable",
  "Disable",
  "DmGameObjectDDF__Disable",
  "dmGameObjectDDF",
  sizeof(DmGameObjectDDF__Disable),
  0,
  dm_game_object_ddf__disable__field_descriptors,
  dm_game_object_ddf__disable__field_indices_by_name,
  0,  dm_game_object_ddf__disable__number_ranges,
  (ProtobufCMessageInit) dm_game_object_ddf__disable__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor dm_game_object_ddf__script_message__field_descriptors[4] =
{
  {
    "descriptor_hash",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    offsetof(DmGameObjectDDF__ScriptMessage, descriptor_hash),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "payload_size",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(DmGameObjectDDF__ScriptMessage, payload_size),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "function",
    3,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(DmGameObjectDDF__ScriptMessage, has_function),
    offsetof(DmGameObjectDDF__ScriptMessage, function),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "unref_function",
    4,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BOOL,
    offsetof(DmGameObjectDDF__ScriptMessage, has_unref_function),
    offsetof(DmGameObjectDDF__ScriptMessage, unref_function),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned dm_game_object_ddf__script_message__field_indices_by_name[] = {
  0,   /* field[0] = descriptor_hash */
  2,   /* field[2] = function */
  1,   /* field[1] = payload_size */
  3,   /* field[3] = unref_function */
};
static const ProtobufCIntRange dm_game_object_ddf__script_message__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 4 }
};
const ProtobufCMessageDescriptor dm_game_object_ddf__script_message__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "dmGameObjectDDF.ScriptMessage",
  "ScriptMessage",
  "DmGameObjectDDF__ScriptMessage",
  "dmGameObjectDDF",
  sizeof(DmGameObjectDDF__ScriptMessage),
  4,
  dm_game_object_ddf__script_message__field_descriptors,
  dm_game_object_ddf__script_message__field_indices_by_name,
  1,  dm_game_object_ddf__script_message__number_ranges,
  (ProtobufCMessageInit) dm_game_object_ddf__script_message__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCEnumValue dm_game_object_ddf__property_type__enum_values_by_number[9] =
{
  { "PROPERTY_TYPE_NUMBER", "DM_GAME_OBJECT_DDF__PROPERTY_TYPE__PROPERTY_TYPE_NUMBER", 0 },
  { "PROPERTY_TYPE_HASH", "DM_GAME_OBJECT_DDF__PROPERTY_TYPE__PROPERTY_TYPE_HASH", 1 },
  { "PROPERTY_TYPE_URL", "DM_GAME_OBJECT_DDF__PROPERTY_TYPE__PROPERTY_TYPE_URL", 2 },
  { "PROPERTY_TYPE_VECTOR3", "DM_GAME_OBJECT_DDF__PROPERTY_TYPE__PROPERTY_TYPE_VECTOR3", 3 },
  { "PROPERTY_TYPE_VECTOR4", "DM_GAME_OBJECT_DDF__PROPERTY_TYPE__PROPERTY_TYPE_VECTOR4", 4 },
  { "PROPERTY_TYPE_QUAT", "DM_GAME_OBJECT_DDF__PROPERTY_TYPE__PROPERTY_TYPE_QUAT", 5 },
  { "PROPERTY_TYPE_BOOLEAN", "DM_GAME_OBJECT_DDF__PROPERTY_TYPE__PROPERTY_TYPE_BOOLEAN", 6 },
  { "PROPERTY_TYPE_MATRIX4", "DM_GAME_OBJECT_DDF__PROPERTY_TYPE__PROPERTY_TYPE_MATRIX4", 7 },
  { "PROPERTY_TYPE_COUNT", "DM_GAME_OBJECT_DDF__PROPERTY_TYPE__PROPERTY_TYPE_COUNT", 8 },
};
static const ProtobufCIntRange dm_game_object_ddf__property_type__value_ranges[] = {
{0, 0},{0, 9}
};
static const ProtobufCEnumValueIndex dm_game_object_ddf__property_type__enum_values_by_name[9] =
{
  { "PROPERTY_TYPE_BOOLEAN", 6 },
  { "PROPERTY_TYPE_COUNT", 8 },
  { "PROPERTY_TYPE_HASH", 1 },
  { "PROPERTY_TYPE_MATRIX4", 7 },
  { "PROPERTY_TYPE_NUMBER", 0 },
  { "PROPERTY_TYPE_QUAT", 5 },
  { "PROPERTY_TYPE_URL", 2 },
  { "PROPERTY_TYPE_VECTOR3", 3 },
  { "PROPERTY_TYPE_VECTOR4", 4 },
};
const ProtobufCEnumDescriptor dm_game_object_ddf__property_type__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "dmGameObjectDDF.PropertyType",
  "PropertyType",
  "DmGameObjectDDF__PropertyType",
  "dmGameObjectDDF",
  9,
  dm_game_object_ddf__property_type__enum_values_by_number,
  9,
  dm_game_object_ddf__property_type__enum_values_by_name,
  1,
  dm_game_object_ddf__property_type__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
