/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: gamesys/gamesys_ddf.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "gamesys/gamesys_ddf.pb-c.h"
void   dm_game_system_ddf__factory_desc__init
                     (DmGameSystemDDF__FactoryDesc         *message)
{
  static const DmGameSystemDDF__FactoryDesc init_value = DM_GAME_SYSTEM_DDF__FACTORY_DESC__INIT;
  *message = init_value;
}
size_t dm_game_system_ddf__factory_desc__get_packed_size
                     (const DmGameSystemDDF__FactoryDesc *message)
{
  assert(message->base.descriptor == &dm_game_system_ddf__factory_desc__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t dm_game_system_ddf__factory_desc__pack
                     (const DmGameSystemDDF__FactoryDesc *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &dm_game_system_ddf__factory_desc__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t dm_game_system_ddf__factory_desc__pack_to_buffer
                     (const DmGameSystemDDF__FactoryDesc *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &dm_game_system_ddf__factory_desc__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
DmGameSystemDDF__FactoryDesc *
       dm_game_system_ddf__factory_desc__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (DmGameSystemDDF__FactoryDesc *)
     protobuf_c_message_unpack (&dm_game_system_ddf__factory_desc__descriptor,
                                allocator, len, data);
}
void   dm_game_system_ddf__factory_desc__free_unpacked
                     (DmGameSystemDDF__FactoryDesc *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &dm_game_system_ddf__factory_desc__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   dm_game_system_ddf__collection_factory_desc__init
                     (DmGameSystemDDF__CollectionFactoryDesc         *message)
{
  static const DmGameSystemDDF__CollectionFactoryDesc init_value = DM_GAME_SYSTEM_DDF__COLLECTION_FACTORY_DESC__INIT;
  *message = init_value;
}
size_t dm_game_system_ddf__collection_factory_desc__get_packed_size
                     (const DmGameSystemDDF__CollectionFactoryDesc *message)
{
  assert(message->base.descriptor == &dm_game_system_ddf__collection_factory_desc__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t dm_game_system_ddf__collection_factory_desc__pack
                     (const DmGameSystemDDF__CollectionFactoryDesc *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &dm_game_system_ddf__collection_factory_desc__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t dm_game_system_ddf__collection_factory_desc__pack_to_buffer
                     (const DmGameSystemDDF__CollectionFactoryDesc *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &dm_game_system_ddf__collection_factory_desc__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
DmGameSystemDDF__CollectionFactoryDesc *
       dm_game_system_ddf__collection_factory_desc__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (DmGameSystemDDF__CollectionFactoryDesc *)
     protobuf_c_message_unpack (&dm_game_system_ddf__collection_factory_desc__descriptor,
                                allocator, len, data);
}
void   dm_game_system_ddf__collection_factory_desc__free_unpacked
                     (DmGameSystemDDF__CollectionFactoryDesc *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &dm_game_system_ddf__collection_factory_desc__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   dm_game_system_ddf__create__init
                     (DmGameSystemDDF__Create         *message)
{
  static const DmGameSystemDDF__Create init_value = DM_GAME_SYSTEM_DDF__CREATE__INIT;
  *message = init_value;
}
size_t dm_game_system_ddf__create__get_packed_size
                     (const DmGameSystemDDF__Create *message)
{
  assert(message->base.descriptor == &dm_game_system_ddf__create__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t dm_game_system_ddf__create__pack
                     (const DmGameSystemDDF__Create *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &dm_game_system_ddf__create__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t dm_game_system_ddf__create__pack_to_buffer
                     (const DmGameSystemDDF__Create *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &dm_game_system_ddf__create__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
DmGameSystemDDF__Create *
       dm_game_system_ddf__create__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (DmGameSystemDDF__Create *)
     protobuf_c_message_unpack (&dm_game_system_ddf__create__descriptor,
                                allocator, len, data);
}
void   dm_game_system_ddf__create__free_unpacked
                     (DmGameSystemDDF__Create *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &dm_game_system_ddf__create__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   dm_game_system_ddf__collection_proxy_desc__init
                     (DmGameSystemDDF__CollectionProxyDesc         *message)
{
  static const DmGameSystemDDF__CollectionProxyDesc init_value = DM_GAME_SYSTEM_DDF__COLLECTION_PROXY_DESC__INIT;
  *message = init_value;
}
size_t dm_game_system_ddf__collection_proxy_desc__get_packed_size
                     (const DmGameSystemDDF__CollectionProxyDesc *message)
{
  assert(message->base.descriptor == &dm_game_system_ddf__collection_proxy_desc__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t dm_game_system_ddf__collection_proxy_desc__pack
                     (const DmGameSystemDDF__CollectionProxyDesc *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &dm_game_system_ddf__collection_proxy_desc__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t dm_game_system_ddf__collection_proxy_desc__pack_to_buffer
                     (const DmGameSystemDDF__CollectionProxyDesc *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &dm_game_system_ddf__collection_proxy_desc__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
DmGameSystemDDF__CollectionProxyDesc *
       dm_game_system_ddf__collection_proxy_desc__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (DmGameSystemDDF__CollectionProxyDesc *)
     protobuf_c_message_unpack (&dm_game_system_ddf__collection_proxy_desc__descriptor,
                                allocator, len, data);
}
void   dm_game_system_ddf__collection_proxy_desc__free_unpacked
                     (DmGameSystemDDF__CollectionProxyDesc *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &dm_game_system_ddf__collection_proxy_desc__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   dm_game_system_ddf__set_time_step__init
                     (DmGameSystemDDF__SetTimeStep         *message)
{
  static const DmGameSystemDDF__SetTimeStep init_value = DM_GAME_SYSTEM_DDF__SET_TIME_STEP__INIT;
  *message = init_value;
}
size_t dm_game_system_ddf__set_time_step__get_packed_size
                     (const DmGameSystemDDF__SetTimeStep *message)
{
  assert(message->base.descriptor == &dm_game_system_ddf__set_time_step__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t dm_game_system_ddf__set_time_step__pack
                     (const DmGameSystemDDF__SetTimeStep *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &dm_game_system_ddf__set_time_step__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t dm_game_system_ddf__set_time_step__pack_to_buffer
                     (const DmGameSystemDDF__SetTimeStep *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &dm_game_system_ddf__set_time_step__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
DmGameSystemDDF__SetTimeStep *
       dm_game_system_ddf__set_time_step__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (DmGameSystemDDF__SetTimeStep *)
     protobuf_c_message_unpack (&dm_game_system_ddf__set_time_step__descriptor,
                                allocator, len, data);
}
void   dm_game_system_ddf__set_time_step__free_unpacked
                     (DmGameSystemDDF__SetTimeStep *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &dm_game_system_ddf__set_time_step__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   dm_game_system_ddf__light_desc__init
                     (DmGameSystemDDF__LightDesc         *message)
{
  static const DmGameSystemDDF__LightDesc init_value = DM_GAME_SYSTEM_DDF__LIGHT_DESC__INIT;
  *message = init_value;
}
size_t dm_game_system_ddf__light_desc__get_packed_size
                     (const DmGameSystemDDF__LightDesc *message)
{
  assert(message->base.descriptor == &dm_game_system_ddf__light_desc__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t dm_game_system_ddf__light_desc__pack
                     (const DmGameSystemDDF__LightDesc *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &dm_game_system_ddf__light_desc__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t dm_game_system_ddf__light_desc__pack_to_buffer
                     (const DmGameSystemDDF__LightDesc *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &dm_game_system_ddf__light_desc__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
DmGameSystemDDF__LightDesc *
       dm_game_system_ddf__light_desc__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (DmGameSystemDDF__LightDesc *)
     protobuf_c_message_unpack (&dm_game_system_ddf__light_desc__descriptor,
                                allocator, len, data);
}
void   dm_game_system_ddf__light_desc__free_unpacked
                     (DmGameSystemDDF__LightDesc *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &dm_game_system_ddf__light_desc__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   dm_game_system_ddf__set_light__init
                     (DmGameSystemDDF__SetLight         *message)
{
  static const DmGameSystemDDF__SetLight init_value = DM_GAME_SYSTEM_DDF__SET_LIGHT__INIT;
  *message = init_value;
}
size_t dm_game_system_ddf__set_light__get_packed_size
                     (const DmGameSystemDDF__SetLight *message)
{
  assert(message->base.descriptor == &dm_game_system_ddf__set_light__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t dm_game_system_ddf__set_light__pack
                     (const DmGameSystemDDF__SetLight *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &dm_game_system_ddf__set_light__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t dm_game_system_ddf__set_light__pack_to_buffer
                     (const DmGameSystemDDF__SetLight *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &dm_game_system_ddf__set_light__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
DmGameSystemDDF__SetLight *
       dm_game_system_ddf__set_light__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (DmGameSystemDDF__SetLight *)
     protobuf_c_message_unpack (&dm_game_system_ddf__set_light__descriptor,
                                allocator, len, data);
}
void   dm_game_system_ddf__set_light__free_unpacked
                     (DmGameSystemDDF__SetLight *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &dm_game_system_ddf__set_light__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   dm_game_system_ddf__set_view_projection__init
                     (DmGameSystemDDF__SetViewProjection         *message)
{
  static const DmGameSystemDDF__SetViewProjection init_value = DM_GAME_SYSTEM_DDF__SET_VIEW_PROJECTION__INIT;
  *message = init_value;
}
size_t dm_game_system_ddf__set_view_projection__get_packed_size
                     (const DmGameSystemDDF__SetViewProjection *message)
{
  assert(message->base.descriptor == &dm_game_system_ddf__set_view_projection__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t dm_game_system_ddf__set_view_projection__pack
                     (const DmGameSystemDDF__SetViewProjection *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &dm_game_system_ddf__set_view_projection__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t dm_game_system_ddf__set_view_projection__pack_to_buffer
                     (const DmGameSystemDDF__SetViewProjection *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &dm_game_system_ddf__set_view_projection__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
DmGameSystemDDF__SetViewProjection *
       dm_game_system_ddf__set_view_projection__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (DmGameSystemDDF__SetViewProjection *)
     protobuf_c_message_unpack (&dm_game_system_ddf__set_view_projection__descriptor,
                                allocator, len, data);
}
void   dm_game_system_ddf__set_view_projection__free_unpacked
                     (DmGameSystemDDF__SetViewProjection *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &dm_game_system_ddf__set_view_projection__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   dm_game_system_ddf__play_sound__init
                     (DmGameSystemDDF__PlaySound         *message)
{
  static const DmGameSystemDDF__PlaySound init_value = DM_GAME_SYSTEM_DDF__PLAY_SOUND__INIT;
  *message = init_value;
}
size_t dm_game_system_ddf__play_sound__get_packed_size
                     (const DmGameSystemDDF__PlaySound *message)
{
  assert(message->base.descriptor == &dm_game_system_ddf__play_sound__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t dm_game_system_ddf__play_sound__pack
                     (const DmGameSystemDDF__PlaySound *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &dm_game_system_ddf__play_sound__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t dm_game_system_ddf__play_sound__pack_to_buffer
                     (const DmGameSystemDDF__PlaySound *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &dm_game_system_ddf__play_sound__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
DmGameSystemDDF__PlaySound *
       dm_game_system_ddf__play_sound__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (DmGameSystemDDF__PlaySound *)
     protobuf_c_message_unpack (&dm_game_system_ddf__play_sound__descriptor,
                                allocator, len, data);
}
void   dm_game_system_ddf__play_sound__free_unpacked
                     (DmGameSystemDDF__PlaySound *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &dm_game_system_ddf__play_sound__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   dm_game_system_ddf__stop_sound__init
                     (DmGameSystemDDF__StopSound         *message)
{
  static const DmGameSystemDDF__StopSound init_value = DM_GAME_SYSTEM_DDF__STOP_SOUND__INIT;
  *message = init_value;
}
size_t dm_game_system_ddf__stop_sound__get_packed_size
                     (const DmGameSystemDDF__StopSound *message)
{
  assert(message->base.descriptor == &dm_game_system_ddf__stop_sound__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t dm_game_system_ddf__stop_sound__pack
                     (const DmGameSystemDDF__StopSound *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &dm_game_system_ddf__stop_sound__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t dm_game_system_ddf__stop_sound__pack_to_buffer
                     (const DmGameSystemDDF__StopSound *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &dm_game_system_ddf__stop_sound__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
DmGameSystemDDF__StopSound *
       dm_game_system_ddf__stop_sound__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (DmGameSystemDDF__StopSound *)
     protobuf_c_message_unpack (&dm_game_system_ddf__stop_sound__descriptor,
                                allocator, len, data);
}
void   dm_game_system_ddf__stop_sound__free_unpacked
                     (DmGameSystemDDF__StopSound *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &dm_game_system_ddf__stop_sound__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   dm_game_system_ddf__pause_sound__init
                     (DmGameSystemDDF__PauseSound         *message)
{
  static const DmGameSystemDDF__PauseSound init_value = DM_GAME_SYSTEM_DDF__PAUSE_SOUND__INIT;
  *message = init_value;
}
size_t dm_game_system_ddf__pause_sound__get_packed_size
                     (const DmGameSystemDDF__PauseSound *message)
{
  assert(message->base.descriptor == &dm_game_system_ddf__pause_sound__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t dm_game_system_ddf__pause_sound__pack
                     (const DmGameSystemDDF__PauseSound *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &dm_game_system_ddf__pause_sound__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t dm_game_system_ddf__pause_sound__pack_to_buffer
                     (const DmGameSystemDDF__PauseSound *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &dm_game_system_ddf__pause_sound__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
DmGameSystemDDF__PauseSound *
       dm_game_system_ddf__pause_sound__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (DmGameSystemDDF__PauseSound *)
     protobuf_c_message_unpack (&dm_game_system_ddf__pause_sound__descriptor,
                                allocator, len, data);
}
void   dm_game_system_ddf__pause_sound__free_unpacked
                     (DmGameSystemDDF__PauseSound *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &dm_game_system_ddf__pause_sound__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   dm_game_system_ddf__sound_done__init
                     (DmGameSystemDDF__SoundDone         *message)
{
  static const DmGameSystemDDF__SoundDone init_value = DM_GAME_SYSTEM_DDF__SOUND_DONE__INIT;
  *message = init_value;
}
size_t dm_game_system_ddf__sound_done__get_packed_size
                     (const DmGameSystemDDF__SoundDone *message)
{
  assert(message->base.descriptor == &dm_game_system_ddf__sound_done__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t dm_game_system_ddf__sound_done__pack
                     (const DmGameSystemDDF__SoundDone *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &dm_game_system_ddf__sound_done__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t dm_game_system_ddf__sound_done__pack_to_buffer
                     (const DmGameSystemDDF__SoundDone *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &dm_game_system_ddf__sound_done__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
DmGameSystemDDF__SoundDone *
       dm_game_system_ddf__sound_done__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (DmGameSystemDDF__SoundDone *)
     protobuf_c_message_unpack (&dm_game_system_ddf__sound_done__descriptor,
                                allocator, len, data);
}
void   dm_game_system_ddf__sound_done__free_unpacked
                     (DmGameSystemDDF__SoundDone *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &dm_game_system_ddf__sound_done__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   dm_game_system_ddf__set_gain__init
                     (DmGameSystemDDF__SetGain         *message)
{
  static const DmGameSystemDDF__SetGain init_value = DM_GAME_SYSTEM_DDF__SET_GAIN__INIT;
  *message = init_value;
}
size_t dm_game_system_ddf__set_gain__get_packed_size
                     (const DmGameSystemDDF__SetGain *message)
{
  assert(message->base.descriptor == &dm_game_system_ddf__set_gain__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t dm_game_system_ddf__set_gain__pack
                     (const DmGameSystemDDF__SetGain *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &dm_game_system_ddf__set_gain__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t dm_game_system_ddf__set_gain__pack_to_buffer
                     (const DmGameSystemDDF__SetGain *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &dm_game_system_ddf__set_gain__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
DmGameSystemDDF__SetGain *
       dm_game_system_ddf__set_gain__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (DmGameSystemDDF__SetGain *)
     protobuf_c_message_unpack (&dm_game_system_ddf__set_gain__descriptor,
                                allocator, len, data);
}
void   dm_game_system_ddf__set_gain__free_unpacked
                     (DmGameSystemDDF__SetGain *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &dm_game_system_ddf__set_gain__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   dm_game_system_ddf__set_pan__init
                     (DmGameSystemDDF__SetPan         *message)
{
  static const DmGameSystemDDF__SetPan init_value = DM_GAME_SYSTEM_DDF__SET_PAN__INIT;
  *message = init_value;
}
size_t dm_game_system_ddf__set_pan__get_packed_size
                     (const DmGameSystemDDF__SetPan *message)
{
  assert(message->base.descriptor == &dm_game_system_ddf__set_pan__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t dm_game_system_ddf__set_pan__pack
                     (const DmGameSystemDDF__SetPan *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &dm_game_system_ddf__set_pan__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t dm_game_system_ddf__set_pan__pack_to_buffer
                     (const DmGameSystemDDF__SetPan *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &dm_game_system_ddf__set_pan__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
DmGameSystemDDF__SetPan *
       dm_game_system_ddf__set_pan__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (DmGameSystemDDF__SetPan *)
     protobuf_c_message_unpack (&dm_game_system_ddf__set_pan__descriptor,
                                allocator, len, data);
}
void   dm_game_system_ddf__set_pan__free_unpacked
                     (DmGameSystemDDF__SetPan *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &dm_game_system_ddf__set_pan__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   dm_game_system_ddf__set_speed__init
                     (DmGameSystemDDF__SetSpeed         *message)
{
  static const DmGameSystemDDF__SetSpeed init_value = DM_GAME_SYSTEM_DDF__SET_SPEED__INIT;
  *message = init_value;
}
size_t dm_game_system_ddf__set_speed__get_packed_size
                     (const DmGameSystemDDF__SetSpeed *message)
{
  assert(message->base.descriptor == &dm_game_system_ddf__set_speed__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t dm_game_system_ddf__set_speed__pack
                     (const DmGameSystemDDF__SetSpeed *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &dm_game_system_ddf__set_speed__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t dm_game_system_ddf__set_speed__pack_to_buffer
                     (const DmGameSystemDDF__SetSpeed *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &dm_game_system_ddf__set_speed__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
DmGameSystemDDF__SetSpeed *
       dm_game_system_ddf__set_speed__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (DmGameSystemDDF__SetSpeed *)
     protobuf_c_message_unpack (&dm_game_system_ddf__set_speed__descriptor,
                                allocator, len, data);
}
void   dm_game_system_ddf__set_speed__free_unpacked
                     (DmGameSystemDDF__SetSpeed *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &dm_game_system_ddf__set_speed__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   dm_game_system_ddf__play_particle_fx__init
                     (DmGameSystemDDF__PlayParticleFX         *message)
{
  static const DmGameSystemDDF__PlayParticleFX init_value = DM_GAME_SYSTEM_DDF__PLAY_PARTICLE_FX__INIT;
  *message = init_value;
}
size_t dm_game_system_ddf__play_particle_fx__get_packed_size
                     (const DmGameSystemDDF__PlayParticleFX *message)
{
  assert(message->base.descriptor == &dm_game_system_ddf__play_particle_fx__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t dm_game_system_ddf__play_particle_fx__pack
                     (const DmGameSystemDDF__PlayParticleFX *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &dm_game_system_ddf__play_particle_fx__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t dm_game_system_ddf__play_particle_fx__pack_to_buffer
                     (const DmGameSystemDDF__PlayParticleFX *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &dm_game_system_ddf__play_particle_fx__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
DmGameSystemDDF__PlayParticleFX *
       dm_game_system_ddf__play_particle_fx__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (DmGameSystemDDF__PlayParticleFX *)
     protobuf_c_message_unpack (&dm_game_system_ddf__play_particle_fx__descriptor,
                                allocator, len, data);
}
void   dm_game_system_ddf__play_particle_fx__free_unpacked
                     (DmGameSystemDDF__PlayParticleFX *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &dm_game_system_ddf__play_particle_fx__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   dm_game_system_ddf__stop_particle_fx__init
                     (DmGameSystemDDF__StopParticleFX         *message)
{
  static const DmGameSystemDDF__StopParticleFX init_value = DM_GAME_SYSTEM_DDF__STOP_PARTICLE_FX__INIT;
  *message = init_value;
}
size_t dm_game_system_ddf__stop_particle_fx__get_packed_size
                     (const DmGameSystemDDF__StopParticleFX *message)
{
  assert(message->base.descriptor == &dm_game_system_ddf__stop_particle_fx__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t dm_game_system_ddf__stop_particle_fx__pack
                     (const DmGameSystemDDF__StopParticleFX *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &dm_game_system_ddf__stop_particle_fx__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t dm_game_system_ddf__stop_particle_fx__pack_to_buffer
                     (const DmGameSystemDDF__StopParticleFX *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &dm_game_system_ddf__stop_particle_fx__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
DmGameSystemDDF__StopParticleFX *
       dm_game_system_ddf__stop_particle_fx__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (DmGameSystemDDF__StopParticleFX *)
     protobuf_c_message_unpack (&dm_game_system_ddf__stop_particle_fx__descriptor,
                                allocator, len, data);
}
void   dm_game_system_ddf__stop_particle_fx__free_unpacked
                     (DmGameSystemDDF__StopParticleFX *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &dm_game_system_ddf__stop_particle_fx__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   dm_game_system_ddf__set_constant_particle_fx__init
                     (DmGameSystemDDF__SetConstantParticleFX         *message)
{
  static const DmGameSystemDDF__SetConstantParticleFX init_value = DM_GAME_SYSTEM_DDF__SET_CONSTANT_PARTICLE_FX__INIT;
  *message = init_value;
}
size_t dm_game_system_ddf__set_constant_particle_fx__get_packed_size
                     (const DmGameSystemDDF__SetConstantParticleFX *message)
{
  assert(message->base.descriptor == &dm_game_system_ddf__set_constant_particle_fx__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t dm_game_system_ddf__set_constant_particle_fx__pack
                     (const DmGameSystemDDF__SetConstantParticleFX *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &dm_game_system_ddf__set_constant_particle_fx__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t dm_game_system_ddf__set_constant_particle_fx__pack_to_buffer
                     (const DmGameSystemDDF__SetConstantParticleFX *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &dm_game_system_ddf__set_constant_particle_fx__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
DmGameSystemDDF__SetConstantParticleFX *
       dm_game_system_ddf__set_constant_particle_fx__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (DmGameSystemDDF__SetConstantParticleFX *)
     protobuf_c_message_unpack (&dm_game_system_ddf__set_constant_particle_fx__descriptor,
                                allocator, len, data);
}
void   dm_game_system_ddf__set_constant_particle_fx__free_unpacked
                     (DmGameSystemDDF__SetConstantParticleFX *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &dm_game_system_ddf__set_constant_particle_fx__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   dm_game_system_ddf__reset_constant_particle_fx__init
                     (DmGameSystemDDF__ResetConstantParticleFX         *message)
{
  static const DmGameSystemDDF__ResetConstantParticleFX init_value = DM_GAME_SYSTEM_DDF__RESET_CONSTANT_PARTICLE_FX__INIT;
  *message = init_value;
}
size_t dm_game_system_ddf__reset_constant_particle_fx__get_packed_size
                     (const DmGameSystemDDF__ResetConstantParticleFX *message)
{
  assert(message->base.descriptor == &dm_game_system_ddf__reset_constant_particle_fx__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t dm_game_system_ddf__reset_constant_particle_fx__pack
                     (const DmGameSystemDDF__ResetConstantParticleFX *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &dm_game_system_ddf__reset_constant_particle_fx__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t dm_game_system_ddf__reset_constant_particle_fx__pack_to_buffer
                     (const DmGameSystemDDF__ResetConstantParticleFX *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &dm_game_system_ddf__reset_constant_particle_fx__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
DmGameSystemDDF__ResetConstantParticleFX *
       dm_game_system_ddf__reset_constant_particle_fx__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (DmGameSystemDDF__ResetConstantParticleFX *)
     protobuf_c_message_unpack (&dm_game_system_ddf__reset_constant_particle_fx__descriptor,
                                allocator, len, data);
}
void   dm_game_system_ddf__reset_constant_particle_fx__free_unpacked
                     (DmGameSystemDDF__ResetConstantParticleFX *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &dm_game_system_ddf__reset_constant_particle_fx__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   dm_game_system_ddf__set_constant__init
                     (DmGameSystemDDF__SetConstant         *message)
{
  static const DmGameSystemDDF__SetConstant init_value = DM_GAME_SYSTEM_DDF__SET_CONSTANT__INIT;
  *message = init_value;
}
size_t dm_game_system_ddf__set_constant__get_packed_size
                     (const DmGameSystemDDF__SetConstant *message)
{
  assert(message->base.descriptor == &dm_game_system_ddf__set_constant__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t dm_game_system_ddf__set_constant__pack
                     (const DmGameSystemDDF__SetConstant *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &dm_game_system_ddf__set_constant__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t dm_game_system_ddf__set_constant__pack_to_buffer
                     (const DmGameSystemDDF__SetConstant *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &dm_game_system_ddf__set_constant__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
DmGameSystemDDF__SetConstant *
       dm_game_system_ddf__set_constant__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (DmGameSystemDDF__SetConstant *)
     protobuf_c_message_unpack (&dm_game_system_ddf__set_constant__descriptor,
                                allocator, len, data);
}
void   dm_game_system_ddf__set_constant__free_unpacked
                     (DmGameSystemDDF__SetConstant *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &dm_game_system_ddf__set_constant__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   dm_game_system_ddf__reset_constant__init
                     (DmGameSystemDDF__ResetConstant         *message)
{
  static const DmGameSystemDDF__ResetConstant init_value = DM_GAME_SYSTEM_DDF__RESET_CONSTANT__INIT;
  *message = init_value;
}
size_t dm_game_system_ddf__reset_constant__get_packed_size
                     (const DmGameSystemDDF__ResetConstant *message)
{
  assert(message->base.descriptor == &dm_game_system_ddf__reset_constant__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t dm_game_system_ddf__reset_constant__pack
                     (const DmGameSystemDDF__ResetConstant *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &dm_game_system_ddf__reset_constant__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t dm_game_system_ddf__reset_constant__pack_to_buffer
                     (const DmGameSystemDDF__ResetConstant *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &dm_game_system_ddf__reset_constant__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
DmGameSystemDDF__ResetConstant *
       dm_game_system_ddf__reset_constant__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (DmGameSystemDDF__ResetConstant *)
     protobuf_c_message_unpack (&dm_game_system_ddf__reset_constant__descriptor,
                                allocator, len, data);
}
void   dm_game_system_ddf__reset_constant__free_unpacked
                     (DmGameSystemDDF__ResetConstant *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &dm_game_system_ddf__reset_constant__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   dm_game_system_ddf__set_scale__init
                     (DmGameSystemDDF__SetScale         *message)
{
  static const DmGameSystemDDF__SetScale init_value = DM_GAME_SYSTEM_DDF__SET_SCALE__INIT;
  *message = init_value;
}
size_t dm_game_system_ddf__set_scale__get_packed_size
                     (const DmGameSystemDDF__SetScale *message)
{
  assert(message->base.descriptor == &dm_game_system_ddf__set_scale__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t dm_game_system_ddf__set_scale__pack
                     (const DmGameSystemDDF__SetScale *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &dm_game_system_ddf__set_scale__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t dm_game_system_ddf__set_scale__pack_to_buffer
                     (const DmGameSystemDDF__SetScale *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &dm_game_system_ddf__set_scale__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
DmGameSystemDDF__SetScale *
       dm_game_system_ddf__set_scale__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (DmGameSystemDDF__SetScale *)
     protobuf_c_message_unpack (&dm_game_system_ddf__set_scale__descriptor,
                                allocator, len, data);
}
void   dm_game_system_ddf__set_scale__free_unpacked
                     (DmGameSystemDDF__SetScale *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &dm_game_system_ddf__set_scale__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const protobuf_c_boolean dm_game_system_ddf__factory_desc__load_dynamically__default_value = 0;
static const ProtobufCFieldDescriptor dm_game_system_ddf__factory_desc__field_descriptors[2] =
{
  {
    "prototype",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(DmGameSystemDDF__FactoryDesc, prototype),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "load_dynamically",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BOOL,
    offsetof(DmGameSystemDDF__FactoryDesc, has_load_dynamically),
    offsetof(DmGameSystemDDF__FactoryDesc, load_dynamically),
    NULL,
    &dm_game_system_ddf__factory_desc__load_dynamically__default_value,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned dm_game_system_ddf__factory_desc__field_indices_by_name[] = {
  1,   /* field[1] = load_dynamically */
  0,   /* field[0] = prototype */
};
static const ProtobufCIntRange dm_game_system_ddf__factory_desc__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor dm_game_system_ddf__factory_desc__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "dmGameSystemDDF.FactoryDesc",
  "FactoryDesc",
  "DmGameSystemDDF__FactoryDesc",
  "dmGameSystemDDF",
  sizeof(DmGameSystemDDF__FactoryDesc),
  2,
  dm_game_system_ddf__factory_desc__field_descriptors,
  dm_game_system_ddf__factory_desc__field_indices_by_name,
  1,  dm_game_system_ddf__factory_desc__number_ranges,
  (ProtobufCMessageInit) dm_game_system_ddf__factory_desc__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const protobuf_c_boolean dm_game_system_ddf__collection_factory_desc__load_dynamically__default_value = 0;
static const ProtobufCFieldDescriptor dm_game_system_ddf__collection_factory_desc__field_descriptors[2] =
{
  {
    "prototype",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(DmGameSystemDDF__CollectionFactoryDesc, prototype),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "load_dynamically",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BOOL,
    offsetof(DmGameSystemDDF__CollectionFactoryDesc, has_load_dynamically),
    offsetof(DmGameSystemDDF__CollectionFactoryDesc, load_dynamically),
    NULL,
    &dm_game_system_ddf__collection_factory_desc__load_dynamically__default_value,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned dm_game_system_ddf__collection_factory_desc__field_indices_by_name[] = {
  1,   /* field[1] = load_dynamically */
  0,   /* field[0] = prototype */
};
static const ProtobufCIntRange dm_game_system_ddf__collection_factory_desc__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor dm_game_system_ddf__collection_factory_desc__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "dmGameSystemDDF.CollectionFactoryDesc",
  "CollectionFactoryDesc",
  "DmGameSystemDDF__CollectionFactoryDesc",
  "dmGameSystemDDF",
  sizeof(DmGameSystemDDF__CollectionFactoryDesc),
  2,
  dm_game_system_ddf__collection_factory_desc__field_descriptors,
  dm_game_system_ddf__collection_factory_desc__field_indices_by_name,
  1,  dm_game_system_ddf__collection_factory_desc__number_ranges,
  (ProtobufCMessageInit) dm_game_system_ddf__collection_factory_desc__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const uint64_t dm_game_system_ddf__create__id__default_value = 0ull;
static const float dm_game_system_ddf__create__scale__default_value = 1;
static const uint32_t dm_game_system_ddf__create__index__default_value = 4294967295u;
static const ProtobufCFieldDescriptor dm_game_system_ddf__create__field_descriptors[6] =
{
  {
    "position",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(DmGameSystemDDF__Create, position),
    &dm_math__point3__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "rotation",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(DmGameSystemDDF__Create, rotation),
    &dm_math__quat__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "id",
    3,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT64,
    offsetof(DmGameSystemDDF__Create, has_id),
    offsetof(DmGameSystemDDF__Create, id),
    NULL,
    &dm_game_system_ddf__create__id__default_value,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "scale",
    4,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_FLOAT,
    offsetof(DmGameSystemDDF__Create, has_scale),
    offsetof(DmGameSystemDDF__Create, scale),
    NULL,
    &dm_game_system_ddf__create__scale__default_value,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "scale3",
    5,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(DmGameSystemDDF__Create, scale3),
    &dm_math__vector3__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "index",
    6,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(DmGameSystemDDF__Create, has_index),
    offsetof(DmGameSystemDDF__Create, index),
    NULL,
    &dm_game_system_ddf__create__index__default_value,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned dm_game_system_ddf__create__field_indices_by_name[] = {
  2,   /* field[2] = id */
  5,   /* field[5] = index */
  0,   /* field[0] = position */
  1,   /* field[1] = rotation */
  3,   /* field[3] = scale */
  4,   /* field[4] = scale3 */
};
static const ProtobufCIntRange dm_game_system_ddf__create__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 6 }
};
const ProtobufCMessageDescriptor dm_game_system_ddf__create__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "dmGameSystemDDF.Create",
  "Create",
  "DmGameSystemDDF__Create",
  "dmGameSystemDDF",
  sizeof(DmGameSystemDDF__Create),
  6,
  dm_game_system_ddf__create__field_descriptors,
  dm_game_system_ddf__create__field_indices_by_name,
  1,  dm_game_system_ddf__create__number_ranges,
  (ProtobufCMessageInit) dm_game_system_ddf__create__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const protobuf_c_boolean dm_game_system_ddf__collection_proxy_desc__exclude__default_value = 0;
static const ProtobufCFieldDescriptor dm_game_system_ddf__collection_proxy_desc__field_descriptors[2] =
{
  {
    "collection",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(DmGameSystemDDF__CollectionProxyDesc, collection),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "exclude",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BOOL,
    offsetof(DmGameSystemDDF__CollectionProxyDesc, has_exclude),
    offsetof(DmGameSystemDDF__CollectionProxyDesc, exclude),
    NULL,
    &dm_game_system_ddf__collection_proxy_desc__exclude__default_value,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned dm_game_system_ddf__collection_proxy_desc__field_indices_by_name[] = {
  0,   /* field[0] = collection */
  1,   /* field[1] = exclude */
};
static const ProtobufCIntRange dm_game_system_ddf__collection_proxy_desc__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor dm_game_system_ddf__collection_proxy_desc__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "dmGameSystemDDF.CollectionProxyDesc",
  "CollectionProxyDesc",
  "DmGameSystemDDF__CollectionProxyDesc",
  "dmGameSystemDDF",
  sizeof(DmGameSystemDDF__CollectionProxyDesc),
  2,
  dm_game_system_ddf__collection_proxy_desc__field_descriptors,
  dm_game_system_ddf__collection_proxy_desc__field_indices_by_name,
  1,  dm_game_system_ddf__collection_proxy_desc__number_ranges,
  (ProtobufCMessageInit) dm_game_system_ddf__collection_proxy_desc__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor dm_game_system_ddf__set_time_step__field_descriptors[2] =
{
  {
    "factor",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_FLOAT,
    0,   /* quantifier_offset */
    offsetof(DmGameSystemDDF__SetTimeStep, factor),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "mode",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(DmGameSystemDDF__SetTimeStep, mode),
    &dm_game_system_ddf__time_step_mode__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned dm_game_system_ddf__set_time_step__field_indices_by_name[] = {
  0,   /* field[0] = factor */
  1,   /* field[1] = mode */
};
static const ProtobufCIntRange dm_game_system_ddf__set_time_step__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor dm_game_system_ddf__set_time_step__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "dmGameSystemDDF.SetTimeStep",
  "SetTimeStep",
  "DmGameSystemDDF__SetTimeStep",
  "dmGameSystemDDF",
  sizeof(DmGameSystemDDF__SetTimeStep),
  2,
  dm_game_system_ddf__set_time_step__field_descriptors,
  dm_game_system_ddf__set_time_step__field_indices_by_name,
  1,  dm_game_system_ddf__set_time_step__number_ranges,
  (ProtobufCMessageInit) dm_game_system_ddf__set_time_step__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor dm_game_system_ddf__light_desc__field_descriptors[9] =
{
  {
    "id",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(DmGameSystemDDF__LightDesc, id),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "type",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(DmGameSystemDDF__LightDesc, type),
    &dm_game_system_ddf__light_type__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "intensity",
    3,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_FLOAT,
    0,   /* quantifier_offset */
    offsetof(DmGameSystemDDF__LightDesc, intensity),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "color",
    4,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(DmGameSystemDDF__LightDesc, color),
    &dm_math__vector3__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "range",
    5,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_FLOAT,
    0,   /* quantifier_offset */
    offsetof(DmGameSystemDDF__LightDesc, range),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "decay",
    6,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_FLOAT,
    0,   /* quantifier_offset */
    offsetof(DmGameSystemDDF__LightDesc, decay),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "cone_angle",
    7,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_FLOAT,
    offsetof(DmGameSystemDDF__LightDesc, has_cone_angle),
    offsetof(DmGameSystemDDF__LightDesc, cone_angle),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "penumbra_angle",
    8,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_FLOAT,
    offsetof(DmGameSystemDDF__LightDesc, has_penumbra_angle),
    offsetof(DmGameSystemDDF__LightDesc, penumbra_angle),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "drop_off",
    9,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_FLOAT,
    offsetof(DmGameSystemDDF__LightDesc, has_drop_off),
    offsetof(DmGameSystemDDF__LightDesc, drop_off),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned dm_game_system_ddf__light_desc__field_indices_by_name[] = {
  3,   /* field[3] = color */
  6,   /* field[6] = cone_angle */
  5,   /* field[5] = decay */
  8,   /* field[8] = drop_off */
  0,   /* field[0] = id */
  2,   /* field[2] = intensity */
  7,   /* field[7] = penumbra_angle */
  4,   /* field[4] = range */
  1,   /* field[1] = type */
};
static const ProtobufCIntRange dm_game_system_ddf__light_desc__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 9 }
};
const ProtobufCMessageDescriptor dm_game_system_ddf__light_desc__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "dmGameSystemDDF.LightDesc",
  "LightDesc",
  "DmGameSystemDDF__LightDesc",
  "dmGameSystemDDF",
  sizeof(DmGameSystemDDF__LightDesc),
  9,
  dm_game_system_ddf__light_desc__field_descriptors,
  dm_game_system_ddf__light_desc__field_indices_by_name,
  1,  dm_game_system_ddf__light_desc__number_ranges,
  (ProtobufCMessageInit) dm_game_system_ddf__light_desc__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor dm_game_system_ddf__set_light__field_descriptors[3] =
{
  {
    "position",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(DmGameSystemDDF__SetLight, position),
    &dm_math__point3__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "rotation",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(DmGameSystemDDF__SetLight, rotation),
    &dm_math__quat__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "light",
    3,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(DmGameSystemDDF__SetLight, light),
    &dm_game_system_ddf__light_desc__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned dm_game_system_ddf__set_light__field_indices_by_name[] = {
  2,   /* field[2] = light */
  0,   /* field[0] = position */
  1,   /* field[1] = rotation */
};
static const ProtobufCIntRange dm_game_system_ddf__set_light__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor dm_game_system_ddf__set_light__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "dmGameSystemDDF.SetLight",
  "SetLight",
  "DmGameSystemDDF__SetLight",
  "dmGameSystemDDF",
  sizeof(DmGameSystemDDF__SetLight),
  3,
  dm_game_system_ddf__set_light__field_descriptors,
  dm_game_system_ddf__set_light__field_indices_by_name,
  1,  dm_game_system_ddf__set_light__number_ranges,
  (ProtobufCMessageInit) dm_game_system_ddf__set_light__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor dm_game_system_ddf__set_view_projection__field_descriptors[3] =
{
  {
    "id",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    offsetof(DmGameSystemDDF__SetViewProjection, id),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "view",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(DmGameSystemDDF__SetViewProjection, view),
    &dm_math__matrix4__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "projection",
    3,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(DmGameSystemDDF__SetViewProjection, projection),
    &dm_math__matrix4__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned dm_game_system_ddf__set_view_projection__field_indices_by_name[] = {
  0,   /* field[0] = id */
  2,   /* field[2] = projection */
  1,   /* field[1] = view */
};
static const ProtobufCIntRange dm_game_system_ddf__set_view_projection__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor dm_game_system_ddf__set_view_projection__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "dmGameSystemDDF.SetViewProjection",
  "SetViewProjection",
  "DmGameSystemDDF__SetViewProjection",
  "dmGameSystemDDF",
  sizeof(DmGameSystemDDF__SetViewProjection),
  3,
  dm_game_system_ddf__set_view_projection__field_descriptors,
  dm_game_system_ddf__set_view_projection__field_indices_by_name,
  1,  dm_game_system_ddf__set_view_projection__number_ranges,
  (ProtobufCMessageInit) dm_game_system_ddf__set_view_projection__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const float dm_game_system_ddf__play_sound__delay__default_value = 0;
static const float dm_game_system_ddf__play_sound__gain__default_value = 1;
static const float dm_game_system_ddf__play_sound__pan__default_value = 0;
static const float dm_game_system_ddf__play_sound__speed__default_value = 1;
static const uint32_t dm_game_system_ddf__play_sound__play_id__default_value = 4294967295u;
static const ProtobufCFieldDescriptor dm_game_system_ddf__play_sound__field_descriptors[5] =
{
  {
    "delay",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_FLOAT,
    offsetof(DmGameSystemDDF__PlaySound, has_delay),
    offsetof(DmGameSystemDDF__PlaySound, delay),
    NULL,
    &dm_game_system_ddf__play_sound__delay__default_value,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "gain",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_FLOAT,
    offsetof(DmGameSystemDDF__PlaySound, has_gain),
    offsetof(DmGameSystemDDF__PlaySound, gain),
    NULL,
    &dm_game_system_ddf__play_sound__gain__default_value,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "pan",
    3,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_FLOAT,
    offsetof(DmGameSystemDDF__PlaySound, has_pan),
    offsetof(DmGameSystemDDF__PlaySound, pan),
    NULL,
    &dm_game_system_ddf__play_sound__pan__default_value,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "speed",
    4,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_FLOAT,
    offsetof(DmGameSystemDDF__PlaySound, has_speed),
    offsetof(DmGameSystemDDF__PlaySound, speed),
    NULL,
    &dm_game_system_ddf__play_sound__speed__default_value,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "play_id",
    5,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(DmGameSystemDDF__PlaySound, has_play_id),
    offsetof(DmGameSystemDDF__PlaySound, play_id),
    NULL,
    &dm_game_system_ddf__play_sound__play_id__default_value,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned dm_game_system_ddf__play_sound__field_indices_by_name[] = {
  0,   /* field[0] = delay */
  1,   /* field[1] = gain */
  2,   /* field[2] = pan */
  4,   /* field[4] = play_id */
  3,   /* field[3] = speed */
};
static const ProtobufCIntRange dm_game_system_ddf__play_sound__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 5 }
};
const ProtobufCMessageDescriptor dm_game_system_ddf__play_sound__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "dmGameSystemDDF.PlaySound",
  "PlaySound",
  "DmGameSystemDDF__PlaySound",
  "dmGameSystemDDF",
  sizeof(DmGameSystemDDF__PlaySound),
  5,
  dm_game_system_ddf__play_sound__field_descriptors,
  dm_game_system_ddf__play_sound__field_indices_by_name,
  1,  dm_game_system_ddf__play_sound__number_ranges,
  (ProtobufCMessageInit) dm_game_system_ddf__play_sound__init,
  NULL,NULL,NULL    /* reserved[123] */
};
#define dm_game_system_ddf__stop_sound__field_descriptors NULL
#define dm_game_system_ddf__stop_sound__field_indices_by_name NULL
#define dm_game_system_ddf__stop_sound__number_ranges NULL
const ProtobufCMessageDescriptor dm_game_system_ddf__stop_sound__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "dmGameSystemDDF.StopSound",
  "StopSound",
  "DmGameSystemDDF__StopSound",
  "dmGameSystemDDF",
  sizeof(DmGameSystemDDF__StopSound),
  0,
  dm_game_system_ddf__stop_sound__field_descriptors,
  dm_game_system_ddf__stop_sound__field_indices_by_name,
  0,  dm_game_system_ddf__stop_sound__number_ranges,
  (ProtobufCMessageInit) dm_game_system_ddf__stop_sound__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const protobuf_c_boolean dm_game_system_ddf__pause_sound__pause__default_value = 1;
static const ProtobufCFieldDescriptor dm_game_system_ddf__pause_sound__field_descriptors[1] =
{
  {
    "pause",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BOOL,
    offsetof(DmGameSystemDDF__PauseSound, has_pause),
    offsetof(DmGameSystemDDF__PauseSound, pause),
    NULL,
    &dm_game_system_ddf__pause_sound__pause__default_value,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned dm_game_system_ddf__pause_sound__field_indices_by_name[] = {
  0,   /* field[0] = pause */
};
static const ProtobufCIntRange dm_game_system_ddf__pause_sound__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor dm_game_system_ddf__pause_sound__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "dmGameSystemDDF.PauseSound",
  "PauseSound",
  "DmGameSystemDDF__PauseSound",
  "dmGameSystemDDF",
  sizeof(DmGameSystemDDF__PauseSound),
  1,
  dm_game_system_ddf__pause_sound__field_descriptors,
  dm_game_system_ddf__pause_sound__field_indices_by_name,
  1,  dm_game_system_ddf__pause_sound__number_ranges,
  (ProtobufCMessageInit) dm_game_system_ddf__pause_sound__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const int32_t dm_game_system_ddf__sound_done__play_id__default_value = 0;
static const ProtobufCFieldDescriptor dm_game_system_ddf__sound_done__field_descriptors[1] =
{
  {
    "play_id",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_INT32,
    offsetof(DmGameSystemDDF__SoundDone, has_play_id),
    offsetof(DmGameSystemDDF__SoundDone, play_id),
    NULL,
    &dm_game_system_ddf__sound_done__play_id__default_value,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned dm_game_system_ddf__sound_done__field_indices_by_name[] = {
  0,   /* field[0] = play_id */
};
static const ProtobufCIntRange dm_game_system_ddf__sound_done__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor dm_game_system_ddf__sound_done__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "dmGameSystemDDF.SoundDone",
  "SoundDone",
  "DmGameSystemDDF__SoundDone",
  "dmGameSystemDDF",
  sizeof(DmGameSystemDDF__SoundDone),
  1,
  dm_game_system_ddf__sound_done__field_descriptors,
  dm_game_system_ddf__sound_done__field_indices_by_name,
  1,  dm_game_system_ddf__sound_done__number_ranges,
  (ProtobufCMessageInit) dm_game_system_ddf__sound_done__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const float dm_game_system_ddf__set_gain__gain__default_value = 1;
static const ProtobufCFieldDescriptor dm_game_system_ddf__set_gain__field_descriptors[1] =
{
  {
    "gain",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_FLOAT,
    offsetof(DmGameSystemDDF__SetGain, has_gain),
    offsetof(DmGameSystemDDF__SetGain, gain),
    NULL,
    &dm_game_system_ddf__set_gain__gain__default_value,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned dm_game_system_ddf__set_gain__field_indices_by_name[] = {
  0,   /* field[0] = gain */
};
static const ProtobufCIntRange dm_game_system_ddf__set_gain__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor dm_game_system_ddf__set_gain__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "dmGameSystemDDF.SetGain",
  "SetGain",
  "DmGameSystemDDF__SetGain",
  "dmGameSystemDDF",
  sizeof(DmGameSystemDDF__SetGain),
  1,
  dm_game_system_ddf__set_gain__field_descriptors,
  dm_game_system_ddf__set_gain__field_indices_by_name,
  1,  dm_game_system_ddf__set_gain__number_ranges,
  (ProtobufCMessageInit) dm_game_system_ddf__set_gain__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const float dm_game_system_ddf__set_pan__pan__default_value = 0;
static const ProtobufCFieldDescriptor dm_game_system_ddf__set_pan__field_descriptors[1] =
{
  {
    "pan",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_FLOAT,
    offsetof(DmGameSystemDDF__SetPan, has_pan),
    offsetof(DmGameSystemDDF__SetPan, pan),
    NULL,
    &dm_game_system_ddf__set_pan__pan__default_value,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned dm_game_system_ddf__set_pan__field_indices_by_name[] = {
  0,   /* field[0] = pan */
};
static const ProtobufCIntRange dm_game_system_ddf__set_pan__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor dm_game_system_ddf__set_pan__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "dmGameSystemDDF.SetPan",
  "SetPan",
  "DmGameSystemDDF__SetPan",
  "dmGameSystemDDF",
  sizeof(DmGameSystemDDF__SetPan),
  1,
  dm_game_system_ddf__set_pan__field_descriptors,
  dm_game_system_ddf__set_pan__field_indices_by_name,
  1,  dm_game_system_ddf__set_pan__number_ranges,
  (ProtobufCMessageInit) dm_game_system_ddf__set_pan__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const float dm_game_system_ddf__set_speed__speed__default_value = 1;
static const ProtobufCFieldDescriptor dm_game_system_ddf__set_speed__field_descriptors[1] =
{
  {
    "speed",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_FLOAT,
    offsetof(DmGameSystemDDF__SetSpeed, has_speed),
    offsetof(DmGameSystemDDF__SetSpeed, speed),
    NULL,
    &dm_game_system_ddf__set_speed__speed__default_value,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned dm_game_system_ddf__set_speed__field_indices_by_name[] = {
  0,   /* field[0] = speed */
};
static const ProtobufCIntRange dm_game_system_ddf__set_speed__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor dm_game_system_ddf__set_speed__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "dmGameSystemDDF.SetSpeed",
  "SetSpeed",
  "DmGameSystemDDF__SetSpeed",
  "dmGameSystemDDF",
  sizeof(DmGameSystemDDF__SetSpeed),
  1,
  dm_game_system_ddf__set_speed__field_descriptors,
  dm_game_system_ddf__set_speed__field_indices_by_name,
  1,  dm_game_system_ddf__set_speed__number_ranges,
  (ProtobufCMessageInit) dm_game_system_ddf__set_speed__init,
  NULL,NULL,NULL    /* reserved[123] */
};
#define dm_game_system_ddf__play_particle_fx__field_descriptors NULL
#define dm_game_system_ddf__play_particle_fx__field_indices_by_name NULL
#define dm_game_system_ddf__play_particle_fx__number_ranges NULL
const ProtobufCMessageDescriptor dm_game_system_ddf__play_particle_fx__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "dmGameSystemDDF.PlayParticleFX",
  "PlayParticleFX",
  "DmGameSystemDDF__PlayParticleFX",
  "dmGameSystemDDF",
  sizeof(DmGameSystemDDF__PlayParticleFX),
  0,
  dm_game_system_ddf__play_particle_fx__field_descriptors,
  dm_game_system_ddf__play_particle_fx__field_indices_by_name,
  0,  dm_game_system_ddf__play_particle_fx__number_ranges,
  (ProtobufCMessageInit) dm_game_system_ddf__play_particle_fx__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const protobuf_c_boolean dm_game_system_ddf__stop_particle_fx__clear_particles__default_value = 0;
static const ProtobufCFieldDescriptor dm_game_system_ddf__stop_particle_fx__field_descriptors[1] =
{
  {
    "clear_particles",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BOOL,
    offsetof(DmGameSystemDDF__StopParticleFX, has_clear_particles),
    offsetof(DmGameSystemDDF__StopParticleFX, clear_particles),
    NULL,
    &dm_game_system_ddf__stop_particle_fx__clear_particles__default_value,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned dm_game_system_ddf__stop_particle_fx__field_indices_by_name[] = {
  0,   /* field[0] = clear_particles */
};
static const ProtobufCIntRange dm_game_system_ddf__stop_particle_fx__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor dm_game_system_ddf__stop_particle_fx__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "dmGameSystemDDF.StopParticleFX",
  "StopParticleFX",
  "DmGameSystemDDF__StopParticleFX",
  "dmGameSystemDDF",
  sizeof(DmGameSystemDDF__StopParticleFX),
  1,
  dm_game_system_ddf__stop_particle_fx__field_descriptors,
  dm_game_system_ddf__stop_particle_fx__field_indices_by_name,
  1,  dm_game_system_ddf__stop_particle_fx__number_ranges,
  (ProtobufCMessageInit) dm_game_system_ddf__stop_particle_fx__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor dm_game_system_ddf__set_constant_particle_fx__field_descriptors[4] =
{
  {
    "emitter_id",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    offsetof(DmGameSystemDDF__SetConstantParticleFX, emitter_id),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "name_hash",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    offsetof(DmGameSystemDDF__SetConstantParticleFX, name_hash),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "value",
    3,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(DmGameSystemDDF__SetConstantParticleFX, value),
    &dm_math__matrix4__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "is_matrix4",
    4,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BOOL,
    offsetof(DmGameSystemDDF__SetConstantParticleFX, has_is_matrix4),
    offsetof(DmGameSystemDDF__SetConstantParticleFX, is_matrix4),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned dm_game_system_ddf__set_constant_particle_fx__field_indices_by_name[] = {
  0,   /* field[0] = emitter_id */
  3,   /* field[3] = is_matrix4 */
  1,   /* field[1] = name_hash */
  2,   /* field[2] = value */
};
static const ProtobufCIntRange dm_game_system_ddf__set_constant_particle_fx__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 4 }
};
const ProtobufCMessageDescriptor dm_game_system_ddf__set_constant_particle_fx__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "dmGameSystemDDF.SetConstantParticleFX",
  "SetConstantParticleFX",
  "DmGameSystemDDF__SetConstantParticleFX",
  "dmGameSystemDDF",
  sizeof(DmGameSystemDDF__SetConstantParticleFX),
  4,
  dm_game_system_ddf__set_constant_particle_fx__field_descriptors,
  dm_game_system_ddf__set_constant_particle_fx__field_indices_by_name,
  1,  dm_game_system_ddf__set_constant_particle_fx__number_ranges,
  (ProtobufCMessageInit) dm_game_system_ddf__set_constant_particle_fx__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor dm_game_system_ddf__reset_constant_particle_fx__field_descriptors[2] =
{
  {
    "emitter_id",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    offsetof(DmGameSystemDDF__ResetConstantParticleFX, emitter_id),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "name_hash",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    offsetof(DmGameSystemDDF__ResetConstantParticleFX, name_hash),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned dm_game_system_ddf__reset_constant_particle_fx__field_indices_by_name[] = {
  0,   /* field[0] = emitter_id */
  1,   /* field[1] = name_hash */
};
static const ProtobufCIntRange dm_game_system_ddf__reset_constant_particle_fx__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor dm_game_system_ddf__reset_constant_particle_fx__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "dmGameSystemDDF.ResetConstantParticleFX",
  "ResetConstantParticleFX",
  "DmGameSystemDDF__ResetConstantParticleFX",
  "dmGameSystemDDF",
  sizeof(DmGameSystemDDF__ResetConstantParticleFX),
  2,
  dm_game_system_ddf__reset_constant_particle_fx__field_descriptors,
  dm_game_system_ddf__reset_constant_particle_fx__field_indices_by_name,
  1,  dm_game_system_ddf__reset_constant_particle_fx__number_ranges,
  (ProtobufCMessageInit) dm_game_system_ddf__reset_constant_particle_fx__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const int32_t dm_game_system_ddf__set_constant__index__default_value = 0;
static const ProtobufCFieldDescriptor dm_game_system_ddf__set_constant__field_descriptors[3] =
{
  {
    "name_hash",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    offsetof(DmGameSystemDDF__SetConstant, name_hash),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "value",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(DmGameSystemDDF__SetConstant, value),
    &dm_math__vector4__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "index",
    3,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_INT32,
    offsetof(DmGameSystemDDF__SetConstant, has_index),
    offsetof(DmGameSystemDDF__SetConstant, index),
    NULL,
    &dm_game_system_ddf__set_constant__index__default_value,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned dm_game_system_ddf__set_constant__field_indices_by_name[] = {
  2,   /* field[2] = index */
  0,   /* field[0] = name_hash */
  1,   /* field[1] = value */
};
static const ProtobufCIntRange dm_game_system_ddf__set_constant__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor dm_game_system_ddf__set_constant__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "dmGameSystemDDF.SetConstant",
  "SetConstant",
  "DmGameSystemDDF__SetConstant",
  "dmGameSystemDDF",
  sizeof(DmGameSystemDDF__SetConstant),
  3,
  dm_game_system_ddf__set_constant__field_descriptors,
  dm_game_system_ddf__set_constant__field_indices_by_name,
  1,  dm_game_system_ddf__set_constant__number_ranges,
  (ProtobufCMessageInit) dm_game_system_ddf__set_constant__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor dm_game_system_ddf__reset_constant__field_descriptors[1] =
{
  {
    "name_hash",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    offsetof(DmGameSystemDDF__ResetConstant, name_hash),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned dm_game_system_ddf__reset_constant__field_indices_by_name[] = {
  0,   /* field[0] = name_hash */
};
static const ProtobufCIntRange dm_game_system_ddf__reset_constant__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor dm_game_system_ddf__reset_constant__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "dmGameSystemDDF.ResetConstant",
  "ResetConstant",
  "DmGameSystemDDF__ResetConstant",
  "dmGameSystemDDF",
  sizeof(DmGameSystemDDF__ResetConstant),
  1,
  dm_game_system_ddf__reset_constant__field_descriptors,
  dm_game_system_ddf__reset_constant__field_indices_by_name,
  1,  dm_game_system_ddf__reset_constant__number_ranges,
  (ProtobufCMessageInit) dm_game_system_ddf__reset_constant__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor dm_game_system_ddf__set_scale__field_descriptors[1] =
{
  {
    "scale",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(DmGameSystemDDF__SetScale, scale),
    &dm_math__vector3__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned dm_game_system_ddf__set_scale__field_indices_by_name[] = {
  0,   /* field[0] = scale */
};
static const ProtobufCIntRange dm_game_system_ddf__set_scale__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor dm_game_system_ddf__set_scale__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "dmGameSystemDDF.SetScale",
  "SetScale",
  "DmGameSystemDDF__SetScale",
  "dmGameSystemDDF",
  sizeof(DmGameSystemDDF__SetScale),
  1,
  dm_game_system_ddf__set_scale__field_descriptors,
  dm_game_system_ddf__set_scale__field_indices_by_name,
  1,  dm_game_system_ddf__set_scale__number_ranges,
  (ProtobufCMessageInit) dm_game_system_ddf__set_scale__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCEnumValue dm_game_system_ddf__time_step_mode__enum_values_by_number[2] =
{
  { "TIME_STEP_MODE_CONTINUOUS", "DM_GAME_SYSTEM_DDF__TIME_STEP_MODE__TIME_STEP_MODE_CONTINUOUS", 0 },
  { "TIME_STEP_MODE_DISCRETE", "DM_GAME_SYSTEM_DDF__TIME_STEP_MODE__TIME_STEP_MODE_DISCRETE", 1 },
};
static const ProtobufCIntRange dm_game_system_ddf__time_step_mode__value_ranges[] = {
{0, 0},{0, 2}
};
static const ProtobufCEnumValueIndex dm_game_system_ddf__time_step_mode__enum_values_by_name[2] =
{
  { "TIME_STEP_MODE_CONTINUOUS", 0 },
  { "TIME_STEP_MODE_DISCRETE", 1 },
};
const ProtobufCEnumDescriptor dm_game_system_ddf__time_step_mode__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "dmGameSystemDDF.TimeStepMode",
  "TimeStepMode",
  "DmGameSystemDDF__TimeStepMode",
  "dmGameSystemDDF",
  2,
  dm_game_system_ddf__time_step_mode__enum_values_by_number,
  2,
  dm_game_system_ddf__time_step_mode__enum_values_by_name,
  1,
  dm_game_system_ddf__time_step_mode__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const ProtobufCEnumValue dm_game_system_ddf__light_type__enum_values_by_number[2] =
{
  { "POINT", "DM_GAME_SYSTEM_DDF__LIGHT_TYPE__POINT", 0 },
  { "SPOT", "DM_GAME_SYSTEM_DDF__LIGHT_TYPE__SPOT", 1 },
};
static const ProtobufCIntRange dm_game_system_ddf__light_type__value_ranges[] = {
{0, 0},{0, 2}
};
static const ProtobufCEnumValueIndex dm_game_system_ddf__light_type__enum_values_by_name[2] =
{
  { "POINT", 0 },
  { "SPOT", 1 },
};
const ProtobufCEnumDescriptor dm_game_system_ddf__light_type__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "dmGameSystemDDF.LightType",
  "LightType",
  "DmGameSystemDDF__LightType",
  "dmGameSystemDDF",
  2,
  dm_game_system_ddf__light_type__enum_values_by_number,
  2,
  dm_game_system_ddf__light_type__enum_values_by_name,
  1,
  dm_game_system_ddf__light_type__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
