/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: gamesys/mesh_ddf.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "gamesys/mesh_ddf.pb-c.h"
void   dm_mesh_ddf__mesh_desc__init
                     (DmMeshDDF__MeshDesc         *message)
{
  static const DmMeshDDF__MeshDesc init_value = DM_MESH_DDF__MESH_DESC__INIT;
  *message = init_value;
}
size_t dm_mesh_ddf__mesh_desc__get_packed_size
                     (const DmMeshDDF__MeshDesc *message)
{
  assert(message->base.descriptor == &dm_mesh_ddf__mesh_desc__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t dm_mesh_ddf__mesh_desc__pack
                     (const DmMeshDDF__MeshDesc *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &dm_mesh_ddf__mesh_desc__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t dm_mesh_ddf__mesh_desc__pack_to_buffer
                     (const DmMeshDDF__MeshDesc *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &dm_mesh_ddf__mesh_desc__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
DmMeshDDF__MeshDesc *
       dm_mesh_ddf__mesh_desc__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (DmMeshDDF__MeshDesc *)
     protobuf_c_message_unpack (&dm_mesh_ddf__mesh_desc__descriptor,
                                allocator, len, data);
}
void   dm_mesh_ddf__mesh_desc__free_unpacked
                     (DmMeshDDF__MeshDesc *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &dm_mesh_ddf__mesh_desc__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCEnumValue dm_mesh_ddf__mesh_desc__primitive_type__enum_values_by_number[3] =
{
  { "PRIMITIVE_LINES", "DM_MESH_DDF__MESH_DESC__PRIMITIVE_TYPE__PRIMITIVE_LINES", 1 },
  { "PRIMITIVE_TRIANGLES", "DM_MESH_DDF__MESH_DESC__PRIMITIVE_TYPE__PRIMITIVE_TRIANGLES", 4 },
  { "PRIMITIVE_TRIANGLE_STRIP", "DM_MESH_DDF__MESH_DESC__PRIMITIVE_TYPE__PRIMITIVE_TRIANGLE_STRIP", 5 },
};
static const ProtobufCIntRange dm_mesh_ddf__mesh_desc__primitive_type__value_ranges[] = {
{1, 0},{4, 1},{0, 3}
};
static const ProtobufCEnumValueIndex dm_mesh_ddf__mesh_desc__primitive_type__enum_values_by_name[3] =
{
  { "PRIMITIVE_LINES", 0 },
  { "PRIMITIVE_TRIANGLES", 1 },
  { "PRIMITIVE_TRIANGLE_STRIP", 2 },
};
const ProtobufCEnumDescriptor dm_mesh_ddf__mesh_desc__primitive_type__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "dmMeshDDF.MeshDesc.PrimitiveType",
  "PrimitiveType",
  "DmMeshDDF__MeshDesc__PrimitiveType",
  "dmMeshDDF",
  3,
  dm_mesh_ddf__mesh_desc__primitive_type__enum_values_by_number,
  3,
  dm_mesh_ddf__mesh_desc__primitive_type__enum_values_by_name,
  2,
  dm_mesh_ddf__mesh_desc__primitive_type__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const DmMeshDDF__MeshDesc__PrimitiveType dm_mesh_ddf__mesh_desc__primitive_type__default_value = DM_MESH_DDF__MESH_DESC__PRIMITIVE_TYPE__PRIMITIVE_TRIANGLES;
static const ProtobufCFieldDescriptor dm_mesh_ddf__mesh_desc__field_descriptors[6] =
{
  {
    "material",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(DmMeshDDF__MeshDesc, material),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "vertices",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(DmMeshDDF__MeshDesc, vertices),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "textures",
    3,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_STRING,
    offsetof(DmMeshDDF__MeshDesc, n_textures),
    offsetof(DmMeshDDF__MeshDesc, textures),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "primitive_type",
    4,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_ENUM,
    offsetof(DmMeshDDF__MeshDesc, has_primitive_type),
    offsetof(DmMeshDDF__MeshDesc, primitive_type),
    &dm_mesh_ddf__mesh_desc__primitive_type__descriptor,
    &dm_mesh_ddf__mesh_desc__primitive_type__default_value,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "position_stream",
    5,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(DmMeshDDF__MeshDesc, position_stream),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "normal_stream",
    6,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(DmMeshDDF__MeshDesc, normal_stream),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned dm_mesh_ddf__mesh_desc__field_indices_by_name[] = {
  0,   /* field[0] = material */
  5,   /* field[5] = normal_stream */
  4,   /* field[4] = position_stream */
  3,   /* field[3] = primitive_type */
  2,   /* field[2] = textures */
  1,   /* field[1] = vertices */
};
static const ProtobufCIntRange dm_mesh_ddf__mesh_desc__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 6 }
};
const ProtobufCMessageDescriptor dm_mesh_ddf__mesh_desc__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "dmMeshDDF.MeshDesc",
  "MeshDesc",
  "DmMeshDDF__MeshDesc",
  "dmMeshDDF",
  sizeof(DmMeshDDF__MeshDesc),
  6,
  dm_mesh_ddf__mesh_desc__field_descriptors,
  dm_mesh_ddf__mesh_desc__field_indices_by_name,
  1,  dm_mesh_ddf__mesh_desc__number_ranges,
  (ProtobufCMessageInit) dm_mesh_ddf__mesh_desc__init,
  NULL,NULL,NULL    /* reserved[123] */
};
