/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: gamesys/physics_ddf.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "gamesys/physics_ddf.pb-c.h"
void   dm_physics_ddf__convex_shape__init
                     (DmPhysicsDDF__ConvexShape         *message)
{
  static const DmPhysicsDDF__ConvexShape init_value = DM_PHYSICS_DDF__CONVEX_SHAPE__INIT;
  *message = init_value;
}
size_t dm_physics_ddf__convex_shape__get_packed_size
                     (const DmPhysicsDDF__ConvexShape *message)
{
  assert(message->base.descriptor == &dm_physics_ddf__convex_shape__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t dm_physics_ddf__convex_shape__pack
                     (const DmPhysicsDDF__ConvexShape *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &dm_physics_ddf__convex_shape__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t dm_physics_ddf__convex_shape__pack_to_buffer
                     (const DmPhysicsDDF__ConvexShape *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &dm_physics_ddf__convex_shape__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
DmPhysicsDDF__ConvexShape *
       dm_physics_ddf__convex_shape__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (DmPhysicsDDF__ConvexShape *)
     protobuf_c_message_unpack (&dm_physics_ddf__convex_shape__descriptor,
                                allocator, len, data);
}
void   dm_physics_ddf__convex_shape__free_unpacked
                     (DmPhysicsDDF__ConvexShape *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &dm_physics_ddf__convex_shape__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   dm_physics_ddf__collision_shape__shape__init
                     (DmPhysicsDDF__CollisionShape__Shape         *message)
{
  static const DmPhysicsDDF__CollisionShape__Shape init_value = DM_PHYSICS_DDF__COLLISION_SHAPE__SHAPE__INIT;
  *message = init_value;
}
void   dm_physics_ddf__collision_shape__init
                     (DmPhysicsDDF__CollisionShape         *message)
{
  static const DmPhysicsDDF__CollisionShape init_value = DM_PHYSICS_DDF__COLLISION_SHAPE__INIT;
  *message = init_value;
}
size_t dm_physics_ddf__collision_shape__get_packed_size
                     (const DmPhysicsDDF__CollisionShape *message)
{
  assert(message->base.descriptor == &dm_physics_ddf__collision_shape__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t dm_physics_ddf__collision_shape__pack
                     (const DmPhysicsDDF__CollisionShape *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &dm_physics_ddf__collision_shape__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t dm_physics_ddf__collision_shape__pack_to_buffer
                     (const DmPhysicsDDF__CollisionShape *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &dm_physics_ddf__collision_shape__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
DmPhysicsDDF__CollisionShape *
       dm_physics_ddf__collision_shape__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (DmPhysicsDDF__CollisionShape *)
     protobuf_c_message_unpack (&dm_physics_ddf__collision_shape__descriptor,
                                allocator, len, data);
}
void   dm_physics_ddf__collision_shape__free_unpacked
                     (DmPhysicsDDF__CollisionShape *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &dm_physics_ddf__collision_shape__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   dm_physics_ddf__collision_object_desc__init
                     (DmPhysicsDDF__CollisionObjectDesc         *message)
{
  static const DmPhysicsDDF__CollisionObjectDesc init_value = DM_PHYSICS_DDF__COLLISION_OBJECT_DESC__INIT;
  *message = init_value;
}
size_t dm_physics_ddf__collision_object_desc__get_packed_size
                     (const DmPhysicsDDF__CollisionObjectDesc *message)
{
  assert(message->base.descriptor == &dm_physics_ddf__collision_object_desc__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t dm_physics_ddf__collision_object_desc__pack
                     (const DmPhysicsDDF__CollisionObjectDesc *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &dm_physics_ddf__collision_object_desc__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t dm_physics_ddf__collision_object_desc__pack_to_buffer
                     (const DmPhysicsDDF__CollisionObjectDesc *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &dm_physics_ddf__collision_object_desc__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
DmPhysicsDDF__CollisionObjectDesc *
       dm_physics_ddf__collision_object_desc__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (DmPhysicsDDF__CollisionObjectDesc *)
     protobuf_c_message_unpack (&dm_physics_ddf__collision_object_desc__descriptor,
                                allocator, len, data);
}
void   dm_physics_ddf__collision_object_desc__free_unpacked
                     (DmPhysicsDDF__CollisionObjectDesc *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &dm_physics_ddf__collision_object_desc__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   dm_physics_ddf__apply_force__init
                     (DmPhysicsDDF__ApplyForce         *message)
{
  static const DmPhysicsDDF__ApplyForce init_value = DM_PHYSICS_DDF__APPLY_FORCE__INIT;
  *message = init_value;
}
size_t dm_physics_ddf__apply_force__get_packed_size
                     (const DmPhysicsDDF__ApplyForce *message)
{
  assert(message->base.descriptor == &dm_physics_ddf__apply_force__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t dm_physics_ddf__apply_force__pack
                     (const DmPhysicsDDF__ApplyForce *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &dm_physics_ddf__apply_force__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t dm_physics_ddf__apply_force__pack_to_buffer
                     (const DmPhysicsDDF__ApplyForce *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &dm_physics_ddf__apply_force__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
DmPhysicsDDF__ApplyForce *
       dm_physics_ddf__apply_force__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (DmPhysicsDDF__ApplyForce *)
     protobuf_c_message_unpack (&dm_physics_ddf__apply_force__descriptor,
                                allocator, len, data);
}
void   dm_physics_ddf__apply_force__free_unpacked
                     (DmPhysicsDDF__ApplyForce *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &dm_physics_ddf__apply_force__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   dm_physics_ddf__collision_response__init
                     (DmPhysicsDDF__CollisionResponse         *message)
{
  static const DmPhysicsDDF__CollisionResponse init_value = DM_PHYSICS_DDF__COLLISION_RESPONSE__INIT;
  *message = init_value;
}
size_t dm_physics_ddf__collision_response__get_packed_size
                     (const DmPhysicsDDF__CollisionResponse *message)
{
  assert(message->base.descriptor == &dm_physics_ddf__collision_response__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t dm_physics_ddf__collision_response__pack
                     (const DmPhysicsDDF__CollisionResponse *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &dm_physics_ddf__collision_response__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t dm_physics_ddf__collision_response__pack_to_buffer
                     (const DmPhysicsDDF__CollisionResponse *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &dm_physics_ddf__collision_response__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
DmPhysicsDDF__CollisionResponse *
       dm_physics_ddf__collision_response__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (DmPhysicsDDF__CollisionResponse *)
     protobuf_c_message_unpack (&dm_physics_ddf__collision_response__descriptor,
                                allocator, len, data);
}
void   dm_physics_ddf__collision_response__free_unpacked
                     (DmPhysicsDDF__CollisionResponse *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &dm_physics_ddf__collision_response__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   dm_physics_ddf__contact_point_response__init
                     (DmPhysicsDDF__ContactPointResponse         *message)
{
  static const DmPhysicsDDF__ContactPointResponse init_value = DM_PHYSICS_DDF__CONTACT_POINT_RESPONSE__INIT;
  *message = init_value;
}
size_t dm_physics_ddf__contact_point_response__get_packed_size
                     (const DmPhysicsDDF__ContactPointResponse *message)
{
  assert(message->base.descriptor == &dm_physics_ddf__contact_point_response__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t dm_physics_ddf__contact_point_response__pack
                     (const DmPhysicsDDF__ContactPointResponse *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &dm_physics_ddf__contact_point_response__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t dm_physics_ddf__contact_point_response__pack_to_buffer
                     (const DmPhysicsDDF__ContactPointResponse *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &dm_physics_ddf__contact_point_response__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
DmPhysicsDDF__ContactPointResponse *
       dm_physics_ddf__contact_point_response__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (DmPhysicsDDF__ContactPointResponse *)
     protobuf_c_message_unpack (&dm_physics_ddf__contact_point_response__descriptor,
                                allocator, len, data);
}
void   dm_physics_ddf__contact_point_response__free_unpacked
                     (DmPhysicsDDF__ContactPointResponse *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &dm_physics_ddf__contact_point_response__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   dm_physics_ddf__trigger_response__init
                     (DmPhysicsDDF__TriggerResponse         *message)
{
  static const DmPhysicsDDF__TriggerResponse init_value = DM_PHYSICS_DDF__TRIGGER_RESPONSE__INIT;
  *message = init_value;
}
size_t dm_physics_ddf__trigger_response__get_packed_size
                     (const DmPhysicsDDF__TriggerResponse *message)
{
  assert(message->base.descriptor == &dm_physics_ddf__trigger_response__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t dm_physics_ddf__trigger_response__pack
                     (const DmPhysicsDDF__TriggerResponse *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &dm_physics_ddf__trigger_response__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t dm_physics_ddf__trigger_response__pack_to_buffer
                     (const DmPhysicsDDF__TriggerResponse *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &dm_physics_ddf__trigger_response__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
DmPhysicsDDF__TriggerResponse *
       dm_physics_ddf__trigger_response__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (DmPhysicsDDF__TriggerResponse *)
     protobuf_c_message_unpack (&dm_physics_ddf__trigger_response__descriptor,
                                allocator, len, data);
}
void   dm_physics_ddf__trigger_response__free_unpacked
                     (DmPhysicsDDF__TriggerResponse *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &dm_physics_ddf__trigger_response__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   dm_physics_ddf__request_ray_cast__init
                     (DmPhysicsDDF__RequestRayCast         *message)
{
  static const DmPhysicsDDF__RequestRayCast init_value = DM_PHYSICS_DDF__REQUEST_RAY_CAST__INIT;
  *message = init_value;
}
size_t dm_physics_ddf__request_ray_cast__get_packed_size
                     (const DmPhysicsDDF__RequestRayCast *message)
{
  assert(message->base.descriptor == &dm_physics_ddf__request_ray_cast__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t dm_physics_ddf__request_ray_cast__pack
                     (const DmPhysicsDDF__RequestRayCast *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &dm_physics_ddf__request_ray_cast__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t dm_physics_ddf__request_ray_cast__pack_to_buffer
                     (const DmPhysicsDDF__RequestRayCast *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &dm_physics_ddf__request_ray_cast__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
DmPhysicsDDF__RequestRayCast *
       dm_physics_ddf__request_ray_cast__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (DmPhysicsDDF__RequestRayCast *)
     protobuf_c_message_unpack (&dm_physics_ddf__request_ray_cast__descriptor,
                                allocator, len, data);
}
void   dm_physics_ddf__request_ray_cast__free_unpacked
                     (DmPhysicsDDF__RequestRayCast *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &dm_physics_ddf__request_ray_cast__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   dm_physics_ddf__ray_cast_response__init
                     (DmPhysicsDDF__RayCastResponse         *message)
{
  static const DmPhysicsDDF__RayCastResponse init_value = DM_PHYSICS_DDF__RAY_CAST_RESPONSE__INIT;
  *message = init_value;
}
size_t dm_physics_ddf__ray_cast_response__get_packed_size
                     (const DmPhysicsDDF__RayCastResponse *message)
{
  assert(message->base.descriptor == &dm_physics_ddf__ray_cast_response__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t dm_physics_ddf__ray_cast_response__pack
                     (const DmPhysicsDDF__RayCastResponse *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &dm_physics_ddf__ray_cast_response__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t dm_physics_ddf__ray_cast_response__pack_to_buffer
                     (const DmPhysicsDDF__RayCastResponse *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &dm_physics_ddf__ray_cast_response__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
DmPhysicsDDF__RayCastResponse *
       dm_physics_ddf__ray_cast_response__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (DmPhysicsDDF__RayCastResponse *)
     protobuf_c_message_unpack (&dm_physics_ddf__ray_cast_response__descriptor,
                                allocator, len, data);
}
void   dm_physics_ddf__ray_cast_response__free_unpacked
                     (DmPhysicsDDF__RayCastResponse *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &dm_physics_ddf__ray_cast_response__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   dm_physics_ddf__ray_cast_missed__init
                     (DmPhysicsDDF__RayCastMissed         *message)
{
  static const DmPhysicsDDF__RayCastMissed init_value = DM_PHYSICS_DDF__RAY_CAST_MISSED__INIT;
  *message = init_value;
}
size_t dm_physics_ddf__ray_cast_missed__get_packed_size
                     (const DmPhysicsDDF__RayCastMissed *message)
{
  assert(message->base.descriptor == &dm_physics_ddf__ray_cast_missed__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t dm_physics_ddf__ray_cast_missed__pack
                     (const DmPhysicsDDF__RayCastMissed *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &dm_physics_ddf__ray_cast_missed__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t dm_physics_ddf__ray_cast_missed__pack_to_buffer
                     (const DmPhysicsDDF__RayCastMissed *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &dm_physics_ddf__ray_cast_missed__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
DmPhysicsDDF__RayCastMissed *
       dm_physics_ddf__ray_cast_missed__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (DmPhysicsDDF__RayCastMissed *)
     protobuf_c_message_unpack (&dm_physics_ddf__ray_cast_missed__descriptor,
                                allocator, len, data);
}
void   dm_physics_ddf__ray_cast_missed__free_unpacked
                     (DmPhysicsDDF__RayCastMissed *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &dm_physics_ddf__ray_cast_missed__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   dm_physics_ddf__request_velocity__init
                     (DmPhysicsDDF__RequestVelocity         *message)
{
  static const DmPhysicsDDF__RequestVelocity init_value = DM_PHYSICS_DDF__REQUEST_VELOCITY__INIT;
  *message = init_value;
}
size_t dm_physics_ddf__request_velocity__get_packed_size
                     (const DmPhysicsDDF__RequestVelocity *message)
{
  assert(message->base.descriptor == &dm_physics_ddf__request_velocity__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t dm_physics_ddf__request_velocity__pack
                     (const DmPhysicsDDF__RequestVelocity *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &dm_physics_ddf__request_velocity__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t dm_physics_ddf__request_velocity__pack_to_buffer
                     (const DmPhysicsDDF__RequestVelocity *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &dm_physics_ddf__request_velocity__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
DmPhysicsDDF__RequestVelocity *
       dm_physics_ddf__request_velocity__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (DmPhysicsDDF__RequestVelocity *)
     protobuf_c_message_unpack (&dm_physics_ddf__request_velocity__descriptor,
                                allocator, len, data);
}
void   dm_physics_ddf__request_velocity__free_unpacked
                     (DmPhysicsDDF__RequestVelocity *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &dm_physics_ddf__request_velocity__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   dm_physics_ddf__velocity_response__init
                     (DmPhysicsDDF__VelocityResponse         *message)
{
  static const DmPhysicsDDF__VelocityResponse init_value = DM_PHYSICS_DDF__VELOCITY_RESPONSE__INIT;
  *message = init_value;
}
size_t dm_physics_ddf__velocity_response__get_packed_size
                     (const DmPhysicsDDF__VelocityResponse *message)
{
  assert(message->base.descriptor == &dm_physics_ddf__velocity_response__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t dm_physics_ddf__velocity_response__pack
                     (const DmPhysicsDDF__VelocityResponse *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &dm_physics_ddf__velocity_response__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t dm_physics_ddf__velocity_response__pack_to_buffer
                     (const DmPhysicsDDF__VelocityResponse *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &dm_physics_ddf__velocity_response__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
DmPhysicsDDF__VelocityResponse *
       dm_physics_ddf__velocity_response__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (DmPhysicsDDF__VelocityResponse *)
     protobuf_c_message_unpack (&dm_physics_ddf__velocity_response__descriptor,
                                allocator, len, data);
}
void   dm_physics_ddf__velocity_response__free_unpacked
                     (DmPhysicsDDF__VelocityResponse *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &dm_physics_ddf__velocity_response__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   dm_physics_ddf__set_grid_shape_hull__init
                     (DmPhysicsDDF__SetGridShapeHull         *message)
{
  static const DmPhysicsDDF__SetGridShapeHull init_value = DM_PHYSICS_DDF__SET_GRID_SHAPE_HULL__INIT;
  *message = init_value;
}
size_t dm_physics_ddf__set_grid_shape_hull__get_packed_size
                     (const DmPhysicsDDF__SetGridShapeHull *message)
{
  assert(message->base.descriptor == &dm_physics_ddf__set_grid_shape_hull__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t dm_physics_ddf__set_grid_shape_hull__pack
                     (const DmPhysicsDDF__SetGridShapeHull *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &dm_physics_ddf__set_grid_shape_hull__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t dm_physics_ddf__set_grid_shape_hull__pack_to_buffer
                     (const DmPhysicsDDF__SetGridShapeHull *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &dm_physics_ddf__set_grid_shape_hull__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
DmPhysicsDDF__SetGridShapeHull *
       dm_physics_ddf__set_grid_shape_hull__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (DmPhysicsDDF__SetGridShapeHull *)
     protobuf_c_message_unpack (&dm_physics_ddf__set_grid_shape_hull__descriptor,
                                allocator, len, data);
}
void   dm_physics_ddf__set_grid_shape_hull__free_unpacked
                     (DmPhysicsDDF__SetGridShapeHull *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &dm_physics_ddf__set_grid_shape_hull__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   dm_physics_ddf__enable_grid_shape_layer__init
                     (DmPhysicsDDF__EnableGridShapeLayer         *message)
{
  static const DmPhysicsDDF__EnableGridShapeLayer init_value = DM_PHYSICS_DDF__ENABLE_GRID_SHAPE_LAYER__INIT;
  *message = init_value;
}
size_t dm_physics_ddf__enable_grid_shape_layer__get_packed_size
                     (const DmPhysicsDDF__EnableGridShapeLayer *message)
{
  assert(message->base.descriptor == &dm_physics_ddf__enable_grid_shape_layer__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t dm_physics_ddf__enable_grid_shape_layer__pack
                     (const DmPhysicsDDF__EnableGridShapeLayer *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &dm_physics_ddf__enable_grid_shape_layer__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t dm_physics_ddf__enable_grid_shape_layer__pack_to_buffer
                     (const DmPhysicsDDF__EnableGridShapeLayer *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &dm_physics_ddf__enable_grid_shape_layer__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
DmPhysicsDDF__EnableGridShapeLayer *
       dm_physics_ddf__enable_grid_shape_layer__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (DmPhysicsDDF__EnableGridShapeLayer *)
     protobuf_c_message_unpack (&dm_physics_ddf__enable_grid_shape_layer__descriptor,
                                allocator, len, data);
}
void   dm_physics_ddf__enable_grid_shape_layer__free_unpacked
                     (DmPhysicsDDF__EnableGridShapeLayer *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &dm_physics_ddf__enable_grid_shape_layer__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCEnumValue dm_physics_ddf__convex_shape__type__enum_values_by_number[4] =
{
  { "TYPE_SPHERE", "DM_PHYSICS_DDF__CONVEX_SHAPE__TYPE__TYPE_SPHERE", 0 },
  { "TYPE_BOX", "DM_PHYSICS_DDF__CONVEX_SHAPE__TYPE__TYPE_BOX", 1 },
  { "TYPE_CAPSULE", "DM_PHYSICS_DDF__CONVEX_SHAPE__TYPE__TYPE_CAPSULE", 2 },
  { "TYPE_HULL", "DM_PHYSICS_DDF__CONVEX_SHAPE__TYPE__TYPE_HULL", 3 },
};
static const ProtobufCIntRange dm_physics_ddf__convex_shape__type__value_ranges[] = {
{0, 0},{0, 4}
};
static const ProtobufCEnumValueIndex dm_physics_ddf__convex_shape__type__enum_values_by_name[4] =
{
  { "TYPE_BOX", 1 },
  { "TYPE_CAPSULE", 2 },
  { "TYPE_HULL", 3 },
  { "TYPE_SPHERE", 0 },
};
const ProtobufCEnumDescriptor dm_physics_ddf__convex_shape__type__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "dmPhysicsDDF.ConvexShape.Type",
  "Type",
  "DmPhysicsDDF__ConvexShape__Type",
  "dmPhysicsDDF",
  4,
  dm_physics_ddf__convex_shape__type__enum_values_by_number,
  4,
  dm_physics_ddf__convex_shape__type__enum_values_by_name,
  1,
  dm_physics_ddf__convex_shape__type__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const ProtobufCFieldDescriptor dm_physics_ddf__convex_shape__field_descriptors[2] =
{
  {
    "shape_type",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(DmPhysicsDDF__ConvexShape, shape_type),
    &dm_physics_ddf__convex_shape__type__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "data",
    2,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_FLOAT,
    offsetof(DmPhysicsDDF__ConvexShape, n_data),
    offsetof(DmPhysicsDDF__ConvexShape, data),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned dm_physics_ddf__convex_shape__field_indices_by_name[] = {
  1,   /* field[1] = data */
  0,   /* field[0] = shape_type */
};
static const ProtobufCIntRange dm_physics_ddf__convex_shape__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor dm_physics_ddf__convex_shape__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "dmPhysicsDDF.ConvexShape",
  "ConvexShape",
  "DmPhysicsDDF__ConvexShape",
  "dmPhysicsDDF",
  sizeof(DmPhysicsDDF__ConvexShape),
  2,
  dm_physics_ddf__convex_shape__field_descriptors,
  dm_physics_ddf__convex_shape__field_indices_by_name,
  1,  dm_physics_ddf__convex_shape__number_ranges,
  (ProtobufCMessageInit) dm_physics_ddf__convex_shape__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor dm_physics_ddf__collision_shape__shape__field_descriptors[5] =
{
  {
    "shape_type",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(DmPhysicsDDF__CollisionShape__Shape, shape_type),
    &dm_physics_ddf__collision_shape__type__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "position",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(DmPhysicsDDF__CollisionShape__Shape, position),
    &dm_math__point3__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "rotation",
    3,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(DmPhysicsDDF__CollisionShape__Shape, rotation),
    &dm_math__quat__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "index",
    4,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(DmPhysicsDDF__CollisionShape__Shape, index),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "count",
    5,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(DmPhysicsDDF__CollisionShape__Shape, count),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned dm_physics_ddf__collision_shape__shape__field_indices_by_name[] = {
  4,   /* field[4] = count */
  3,   /* field[3] = index */
  1,   /* field[1] = position */
  2,   /* field[2] = rotation */
  0,   /* field[0] = shape_type */
};
static const ProtobufCIntRange dm_physics_ddf__collision_shape__shape__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 5 }
};
const ProtobufCMessageDescriptor dm_physics_ddf__collision_shape__shape__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "dmPhysicsDDF.CollisionShape.Shape",
  "Shape",
  "DmPhysicsDDF__CollisionShape__Shape",
  "dmPhysicsDDF",
  sizeof(DmPhysicsDDF__CollisionShape__Shape),
  5,
  dm_physics_ddf__collision_shape__shape__field_descriptors,
  dm_physics_ddf__collision_shape__shape__field_indices_by_name,
  1,  dm_physics_ddf__collision_shape__shape__number_ranges,
  (ProtobufCMessageInit) dm_physics_ddf__collision_shape__shape__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCEnumValue dm_physics_ddf__collision_shape__type__enum_values_by_number[4] =
{
  { "TYPE_SPHERE", "DM_PHYSICS_DDF__COLLISION_SHAPE__TYPE__TYPE_SPHERE", 0 },
  { "TYPE_BOX", "DM_PHYSICS_DDF__COLLISION_SHAPE__TYPE__TYPE_BOX", 1 },
  { "TYPE_CAPSULE", "DM_PHYSICS_DDF__COLLISION_SHAPE__TYPE__TYPE_CAPSULE", 2 },
  { "TYPE_HULL", "DM_PHYSICS_DDF__COLLISION_SHAPE__TYPE__TYPE_HULL", 3 },
};
static const ProtobufCIntRange dm_physics_ddf__collision_shape__type__value_ranges[] = {
{0, 0},{0, 4}
};
static const ProtobufCEnumValueIndex dm_physics_ddf__collision_shape__type__enum_values_by_name[4] =
{
  { "TYPE_BOX", 1 },
  { "TYPE_CAPSULE", 2 },
  { "TYPE_HULL", 3 },
  { "TYPE_SPHERE", 0 },
};
const ProtobufCEnumDescriptor dm_physics_ddf__collision_shape__type__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "dmPhysicsDDF.CollisionShape.Type",
  "Type",
  "DmPhysicsDDF__CollisionShape__Type",
  "dmPhysicsDDF",
  4,
  dm_physics_ddf__collision_shape__type__enum_values_by_number,
  4,
  dm_physics_ddf__collision_shape__type__enum_values_by_name,
  1,
  dm_physics_ddf__collision_shape__type__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const ProtobufCFieldDescriptor dm_physics_ddf__collision_shape__field_descriptors[2] =
{
  {
    "shapes",
    1,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(DmPhysicsDDF__CollisionShape, n_shapes),
    offsetof(DmPhysicsDDF__CollisionShape, shapes),
    &dm_physics_ddf__collision_shape__shape__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "data",
    2,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_FLOAT,
    offsetof(DmPhysicsDDF__CollisionShape, n_data),
    offsetof(DmPhysicsDDF__CollisionShape, data),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned dm_physics_ddf__collision_shape__field_indices_by_name[] = {
  1,   /* field[1] = data */
  0,   /* field[0] = shapes */
};
static const ProtobufCIntRange dm_physics_ddf__collision_shape__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor dm_physics_ddf__collision_shape__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "dmPhysicsDDF.CollisionShape",
  "CollisionShape",
  "DmPhysicsDDF__CollisionShape",
  "dmPhysicsDDF",
  sizeof(DmPhysicsDDF__CollisionShape),
  2,
  dm_physics_ddf__collision_shape__field_descriptors,
  dm_physics_ddf__collision_shape__field_indices_by_name,
  1,  dm_physics_ddf__collision_shape__number_ranges,
  (ProtobufCMessageInit) dm_physics_ddf__collision_shape__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const float dm_physics_ddf__collision_object_desc__linear_damping__default_value = 0;
static const float dm_physics_ddf__collision_object_desc__angular_damping__default_value = 0;
static const protobuf_c_boolean dm_physics_ddf__collision_object_desc__locked_rotation__default_value = 0;
static const protobuf_c_boolean dm_physics_ddf__collision_object_desc__bullet__default_value = 0;
static const ProtobufCFieldDescriptor dm_physics_ddf__collision_object_desc__field_descriptors[12] =
{
  {
    "collision_shape",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(DmPhysicsDDF__CollisionObjectDesc, collision_shape),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "type",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(DmPhysicsDDF__CollisionObjectDesc, type),
    &dm_physics_ddf__collision_object_type__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "mass",
    3,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_FLOAT,
    0,   /* quantifier_offset */
    offsetof(DmPhysicsDDF__CollisionObjectDesc, mass),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "friction",
    4,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_FLOAT,
    0,   /* quantifier_offset */
    offsetof(DmPhysicsDDF__CollisionObjectDesc, friction),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "restitution",
    5,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_FLOAT,
    0,   /* quantifier_offset */
    offsetof(DmPhysicsDDF__CollisionObjectDesc, restitution),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "group",
    6,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(DmPhysicsDDF__CollisionObjectDesc, group),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "mask",
    7,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_STRING,
    offsetof(DmPhysicsDDF__CollisionObjectDesc, n_mask),
    offsetof(DmPhysicsDDF__CollisionObjectDesc, mask),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "embedded_collision_shape",
    8,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(DmPhysicsDDF__CollisionObjectDesc, embedded_collision_shape),
    &dm_physics_ddf__collision_shape__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "linear_damping",
    9,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_FLOAT,
    offsetof(DmPhysicsDDF__CollisionObjectDesc, has_linear_damping),
    offsetof(DmPhysicsDDF__CollisionObjectDesc, linear_damping),
    NULL,
    &dm_physics_ddf__collision_object_desc__linear_damping__default_value,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "angular_damping",
    10,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_FLOAT,
    offsetof(DmPhysicsDDF__CollisionObjectDesc, has_angular_damping),
    offsetof(DmPhysicsDDF__CollisionObjectDesc, angular_damping),
    NULL,
    &dm_physics_ddf__collision_object_desc__angular_damping__default_value,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "locked_rotation",
    11,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BOOL,
    offsetof(DmPhysicsDDF__CollisionObjectDesc, has_locked_rotation),
    offsetof(DmPhysicsDDF__CollisionObjectDesc, locked_rotation),
    NULL,
    &dm_physics_ddf__collision_object_desc__locked_rotation__default_value,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "bullet",
    12,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BOOL,
    offsetof(DmPhysicsDDF__CollisionObjectDesc, has_bullet),
    offsetof(DmPhysicsDDF__CollisionObjectDesc, bullet),
    NULL,
    &dm_physics_ddf__collision_object_desc__bullet__default_value,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned dm_physics_ddf__collision_object_desc__field_indices_by_name[] = {
  9,   /* field[9] = angular_damping */
  11,   /* field[11] = bullet */
  0,   /* field[0] = collision_shape */
  7,   /* field[7] = embedded_collision_shape */
  3,   /* field[3] = friction */
  5,   /* field[5] = group */
  8,   /* field[8] = linear_damping */
  10,   /* field[10] = locked_rotation */
  6,   /* field[6] = mask */
  2,   /* field[2] = mass */
  4,   /* field[4] = restitution */
  1,   /* field[1] = type */
};
static const ProtobufCIntRange dm_physics_ddf__collision_object_desc__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 12 }
};
const ProtobufCMessageDescriptor dm_physics_ddf__collision_object_desc__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "dmPhysicsDDF.CollisionObjectDesc",
  "CollisionObjectDesc",
  "DmPhysicsDDF__CollisionObjectDesc",
  "dmPhysicsDDF",
  sizeof(DmPhysicsDDF__CollisionObjectDesc),
  12,
  dm_physics_ddf__collision_object_desc__field_descriptors,
  dm_physics_ddf__collision_object_desc__field_indices_by_name,
  1,  dm_physics_ddf__collision_object_desc__number_ranges,
  (ProtobufCMessageInit) dm_physics_ddf__collision_object_desc__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor dm_physics_ddf__apply_force__field_descriptors[2] =
{
  {
    "force",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(DmPhysicsDDF__ApplyForce, force),
    &dm_math__vector3__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "position",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(DmPhysicsDDF__ApplyForce, position),
    &dm_math__point3__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned dm_physics_ddf__apply_force__field_indices_by_name[] = {
  0,   /* field[0] = force */
  1,   /* field[1] = position */
};
static const ProtobufCIntRange dm_physics_ddf__apply_force__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor dm_physics_ddf__apply_force__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "dmPhysicsDDF.ApplyForce",
  "ApplyForce",
  "DmPhysicsDDF__ApplyForce",
  "dmPhysicsDDF",
  sizeof(DmPhysicsDDF__ApplyForce),
  2,
  dm_physics_ddf__apply_force__field_descriptors,
  dm_physics_ddf__apply_force__field_indices_by_name,
  1,  dm_physics_ddf__apply_force__number_ranges,
  (ProtobufCMessageInit) dm_physics_ddf__apply_force__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor dm_physics_ddf__collision_response__field_descriptors[5] =
{
  {
    "other_id",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    offsetof(DmPhysicsDDF__CollisionResponse, other_id),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "group",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    offsetof(DmPhysicsDDF__CollisionResponse, group),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "other_position",
    3,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(DmPhysicsDDF__CollisionResponse, other_position),
    &dm_math__point3__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "other_group",
    4,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    offsetof(DmPhysicsDDF__CollisionResponse, other_group),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "own_group",
    5,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    offsetof(DmPhysicsDDF__CollisionResponse, own_group),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned dm_physics_ddf__collision_response__field_indices_by_name[] = {
  1,   /* field[1] = group */
  3,   /* field[3] = other_group */
  0,   /* field[0] = other_id */
  2,   /* field[2] = other_position */
  4,   /* field[4] = own_group */
};
static const ProtobufCIntRange dm_physics_ddf__collision_response__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 5 }
};
const ProtobufCMessageDescriptor dm_physics_ddf__collision_response__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "dmPhysicsDDF.CollisionResponse",
  "CollisionResponse",
  "DmPhysicsDDF__CollisionResponse",
  "dmPhysicsDDF",
  sizeof(DmPhysicsDDF__CollisionResponse),
  5,
  dm_physics_ddf__collision_response__field_descriptors,
  dm_physics_ddf__collision_response__field_indices_by_name,
  1,  dm_physics_ddf__collision_response__number_ranges,
  (ProtobufCMessageInit) dm_physics_ddf__collision_response__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor dm_physics_ddf__contact_point_response__field_descriptors[13] =
{
  {
    "position",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(DmPhysicsDDF__ContactPointResponse, position),
    &dm_math__point3__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "normal",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(DmPhysicsDDF__ContactPointResponse, normal),
    &dm_math__vector3__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "relative_velocity",
    3,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(DmPhysicsDDF__ContactPointResponse, relative_velocity),
    &dm_math__vector3__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "distance",
    4,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_FLOAT,
    0,   /* quantifier_offset */
    offsetof(DmPhysicsDDF__ContactPointResponse, distance),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "applied_impulse",
    5,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_FLOAT,
    0,   /* quantifier_offset */
    offsetof(DmPhysicsDDF__ContactPointResponse, applied_impulse),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "life_time",
    6,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_FLOAT,
    0,   /* quantifier_offset */
    offsetof(DmPhysicsDDF__ContactPointResponse, life_time),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "mass",
    7,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_FLOAT,
    0,   /* quantifier_offset */
    offsetof(DmPhysicsDDF__ContactPointResponse, mass),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "other_mass",
    8,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_FLOAT,
    0,   /* quantifier_offset */
    offsetof(DmPhysicsDDF__ContactPointResponse, other_mass),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "other_id",
    9,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    offsetof(DmPhysicsDDF__ContactPointResponse, other_id),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "other_position",
    10,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(DmPhysicsDDF__ContactPointResponse, other_position),
    &dm_math__point3__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "group",
    11,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    offsetof(DmPhysicsDDF__ContactPointResponse, group),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "other_group",
    12,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    offsetof(DmPhysicsDDF__ContactPointResponse, other_group),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "own_group",
    13,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    offsetof(DmPhysicsDDF__ContactPointResponse, own_group),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned dm_physics_ddf__contact_point_response__field_indices_by_name[] = {
  4,   /* field[4] = applied_impulse */
  3,   /* field[3] = distance */
  10,   /* field[10] = group */
  5,   /* field[5] = life_time */
  6,   /* field[6] = mass */
  1,   /* field[1] = normal */
  11,   /* field[11] = other_group */
  8,   /* field[8] = other_id */
  7,   /* field[7] = other_mass */
  9,   /* field[9] = other_position */
  12,   /* field[12] = own_group */
  0,   /* field[0] = position */
  2,   /* field[2] = relative_velocity */
};
static const ProtobufCIntRange dm_physics_ddf__contact_point_response__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 13 }
};
const ProtobufCMessageDescriptor dm_physics_ddf__contact_point_response__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "dmPhysicsDDF.ContactPointResponse",
  "ContactPointResponse",
  "DmPhysicsDDF__ContactPointResponse",
  "dmPhysicsDDF",
  sizeof(DmPhysicsDDF__ContactPointResponse),
  13,
  dm_physics_ddf__contact_point_response__field_descriptors,
  dm_physics_ddf__contact_point_response__field_indices_by_name,
  1,  dm_physics_ddf__contact_point_response__number_ranges,
  (ProtobufCMessageInit) dm_physics_ddf__contact_point_response__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor dm_physics_ddf__trigger_response__field_descriptors[5] =
{
  {
    "other_id",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    offsetof(DmPhysicsDDF__TriggerResponse, other_id),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "enter",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_BOOL,
    0,   /* quantifier_offset */
    offsetof(DmPhysicsDDF__TriggerResponse, enter),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "group",
    3,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    offsetof(DmPhysicsDDF__TriggerResponse, group),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "other_group",
    4,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    offsetof(DmPhysicsDDF__TriggerResponse, other_group),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "own_group",
    5,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    offsetof(DmPhysicsDDF__TriggerResponse, own_group),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned dm_physics_ddf__trigger_response__field_indices_by_name[] = {
  1,   /* field[1] = enter */
  2,   /* field[2] = group */
  3,   /* field[3] = other_group */
  0,   /* field[0] = other_id */
  4,   /* field[4] = own_group */
};
static const ProtobufCIntRange dm_physics_ddf__trigger_response__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 5 }
};
const ProtobufCMessageDescriptor dm_physics_ddf__trigger_response__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "dmPhysicsDDF.TriggerResponse",
  "TriggerResponse",
  "DmPhysicsDDF__TriggerResponse",
  "dmPhysicsDDF",
  sizeof(DmPhysicsDDF__TriggerResponse),
  5,
  dm_physics_ddf__trigger_response__field_descriptors,
  dm_physics_ddf__trigger_response__field_indices_by_name,
  1,  dm_physics_ddf__trigger_response__number_ranges,
  (ProtobufCMessageInit) dm_physics_ddf__trigger_response__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor dm_physics_ddf__request_ray_cast__field_descriptors[4] =
{
  {
    "from",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(DmPhysicsDDF__RequestRayCast, from),
    &dm_math__point3__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "to",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(DmPhysicsDDF__RequestRayCast, to),
    &dm_math__point3__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "mask",
    3,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(DmPhysicsDDF__RequestRayCast, mask),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "request_id",
    4,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(DmPhysicsDDF__RequestRayCast, request_id),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned dm_physics_ddf__request_ray_cast__field_indices_by_name[] = {
  0,   /* field[0] = from */
  2,   /* field[2] = mask */
  3,   /* field[3] = request_id */
  1,   /* field[1] = to */
};
static const ProtobufCIntRange dm_physics_ddf__request_ray_cast__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 4 }
};
const ProtobufCMessageDescriptor dm_physics_ddf__request_ray_cast__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "dmPhysicsDDF.RequestRayCast",
  "RequestRayCast",
  "DmPhysicsDDF__RequestRayCast",
  "dmPhysicsDDF",
  sizeof(DmPhysicsDDF__RequestRayCast),
  4,
  dm_physics_ddf__request_ray_cast__field_descriptors,
  dm_physics_ddf__request_ray_cast__field_indices_by_name,
  1,  dm_physics_ddf__request_ray_cast__number_ranges,
  (ProtobufCMessageInit) dm_physics_ddf__request_ray_cast__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor dm_physics_ddf__ray_cast_response__field_descriptors[6] =
{
  {
    "fraction",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_FLOAT,
    0,   /* quantifier_offset */
    offsetof(DmPhysicsDDF__RayCastResponse, fraction),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "position",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(DmPhysicsDDF__RayCastResponse, position),
    &dm_math__point3__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "normal",
    3,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(DmPhysicsDDF__RayCastResponse, normal),
    &dm_math__vector3__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "id",
    4,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    offsetof(DmPhysicsDDF__RayCastResponse, id),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "group",
    5,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    offsetof(DmPhysicsDDF__RayCastResponse, group),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "request_id",
    6,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(DmPhysicsDDF__RayCastResponse, request_id),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned dm_physics_ddf__ray_cast_response__field_indices_by_name[] = {
  0,   /* field[0] = fraction */
  4,   /* field[4] = group */
  3,   /* field[3] = id */
  2,   /* field[2] = normal */
  1,   /* field[1] = position */
  5,   /* field[5] = request_id */
};
static const ProtobufCIntRange dm_physics_ddf__ray_cast_response__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 6 }
};
const ProtobufCMessageDescriptor dm_physics_ddf__ray_cast_response__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "dmPhysicsDDF.RayCastResponse",
  "RayCastResponse",
  "DmPhysicsDDF__RayCastResponse",
  "dmPhysicsDDF",
  sizeof(DmPhysicsDDF__RayCastResponse),
  6,
  dm_physics_ddf__ray_cast_response__field_descriptors,
  dm_physics_ddf__ray_cast_response__field_indices_by_name,
  1,  dm_physics_ddf__ray_cast_response__number_ranges,
  (ProtobufCMessageInit) dm_physics_ddf__ray_cast_response__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor dm_physics_ddf__ray_cast_missed__field_descriptors[1] =
{
  {
    "request_id",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(DmPhysicsDDF__RayCastMissed, request_id),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned dm_physics_ddf__ray_cast_missed__field_indices_by_name[] = {
  0,   /* field[0] = request_id */
};
static const ProtobufCIntRange dm_physics_ddf__ray_cast_missed__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor dm_physics_ddf__ray_cast_missed__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "dmPhysicsDDF.RayCastMissed",
  "RayCastMissed",
  "DmPhysicsDDF__RayCastMissed",
  "dmPhysicsDDF",
  sizeof(DmPhysicsDDF__RayCastMissed),
  1,
  dm_physics_ddf__ray_cast_missed__field_descriptors,
  dm_physics_ddf__ray_cast_missed__field_indices_by_name,
  1,  dm_physics_ddf__ray_cast_missed__number_ranges,
  (ProtobufCMessageInit) dm_physics_ddf__ray_cast_missed__init,
  NULL,NULL,NULL    /* reserved[123] */
};
#define dm_physics_ddf__request_velocity__field_descriptors NULL
#define dm_physics_ddf__request_velocity__field_indices_by_name NULL
#define dm_physics_ddf__request_velocity__number_ranges NULL
const ProtobufCMessageDescriptor dm_physics_ddf__request_velocity__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "dmPhysicsDDF.RequestVelocity",
  "RequestVelocity",
  "DmPhysicsDDF__RequestVelocity",
  "dmPhysicsDDF",
  sizeof(DmPhysicsDDF__RequestVelocity),
  0,
  dm_physics_ddf__request_velocity__field_descriptors,
  dm_physics_ddf__request_velocity__field_indices_by_name,
  0,  dm_physics_ddf__request_velocity__number_ranges,
  (ProtobufCMessageInit) dm_physics_ddf__request_velocity__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor dm_physics_ddf__velocity_response__field_descriptors[2] =
{
  {
    "linear_velocity",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(DmPhysicsDDF__VelocityResponse, linear_velocity),
    &dm_math__vector3__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "angular_velocity",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(DmPhysicsDDF__VelocityResponse, angular_velocity),
    &dm_math__vector3__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned dm_physics_ddf__velocity_response__field_indices_by_name[] = {
  1,   /* field[1] = angular_velocity */
  0,   /* field[0] = linear_velocity */
};
static const ProtobufCIntRange dm_physics_ddf__velocity_response__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor dm_physics_ddf__velocity_response__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "dmPhysicsDDF.VelocityResponse",
  "VelocityResponse",
  "DmPhysicsDDF__VelocityResponse",
  "dmPhysicsDDF",
  sizeof(DmPhysicsDDF__VelocityResponse),
  2,
  dm_physics_ddf__velocity_response__field_descriptors,
  dm_physics_ddf__velocity_response__field_indices_by_name,
  1,  dm_physics_ddf__velocity_response__number_ranges,
  (ProtobufCMessageInit) dm_physics_ddf__velocity_response__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor dm_physics_ddf__set_grid_shape_hull__field_descriptors[7] =
{
  {
    "shape",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(DmPhysicsDDF__SetGridShapeHull, shape),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "row",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(DmPhysicsDDF__SetGridShapeHull, row),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "column",
    3,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(DmPhysicsDDF__SetGridShapeHull, column),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "hull",
    4,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(DmPhysicsDDF__SetGridShapeHull, hull),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "flip_horizontal",
    5,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(DmPhysicsDDF__SetGridShapeHull, flip_horizontal),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "flip_vertical",
    6,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(DmPhysicsDDF__SetGridShapeHull, flip_vertical),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "rotate90",
    7,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(DmPhysicsDDF__SetGridShapeHull, rotate90),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned dm_physics_ddf__set_grid_shape_hull__field_indices_by_name[] = {
  2,   /* field[2] = column */
  4,   /* field[4] = flip_horizontal */
  5,   /* field[5] = flip_vertical */
  3,   /* field[3] = hull */
  6,   /* field[6] = rotate90 */
  1,   /* field[1] = row */
  0,   /* field[0] = shape */
};
static const ProtobufCIntRange dm_physics_ddf__set_grid_shape_hull__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 7 }
};
const ProtobufCMessageDescriptor dm_physics_ddf__set_grid_shape_hull__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "dmPhysicsDDF.SetGridShapeHull",
  "SetGridShapeHull",
  "DmPhysicsDDF__SetGridShapeHull",
  "dmPhysicsDDF",
  sizeof(DmPhysicsDDF__SetGridShapeHull),
  7,
  dm_physics_ddf__set_grid_shape_hull__field_descriptors,
  dm_physics_ddf__set_grid_shape_hull__field_indices_by_name,
  1,  dm_physics_ddf__set_grid_shape_hull__number_ranges,
  (ProtobufCMessageInit) dm_physics_ddf__set_grid_shape_hull__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor dm_physics_ddf__enable_grid_shape_layer__field_descriptors[2] =
{
  {
    "shape",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(DmPhysicsDDF__EnableGridShapeLayer, shape),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "enable",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(DmPhysicsDDF__EnableGridShapeLayer, enable),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned dm_physics_ddf__enable_grid_shape_layer__field_indices_by_name[] = {
  1,   /* field[1] = enable */
  0,   /* field[0] = shape */
};
static const ProtobufCIntRange dm_physics_ddf__enable_grid_shape_layer__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor dm_physics_ddf__enable_grid_shape_layer__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "dmPhysicsDDF.EnableGridShapeLayer",
  "EnableGridShapeLayer",
  "DmPhysicsDDF__EnableGridShapeLayer",
  "dmPhysicsDDF",
  sizeof(DmPhysicsDDF__EnableGridShapeLayer),
  2,
  dm_physics_ddf__enable_grid_shape_layer__field_descriptors,
  dm_physics_ddf__enable_grid_shape_layer__field_indices_by_name,
  1,  dm_physics_ddf__enable_grid_shape_layer__number_ranges,
  (ProtobufCMessageInit) dm_physics_ddf__enable_grid_shape_layer__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCEnumValue dm_physics_ddf__collision_object_type__enum_values_by_number[4] =
{
  { "COLLISION_OBJECT_TYPE_DYNAMIC", "DM_PHYSICS_DDF__COLLISION_OBJECT_TYPE__COLLISION_OBJECT_TYPE_DYNAMIC", 0 },
  { "COLLISION_OBJECT_TYPE_KINEMATIC", "DM_PHYSICS_DDF__COLLISION_OBJECT_TYPE__COLLISION_OBJECT_TYPE_KINEMATIC", 1 },
  { "COLLISION_OBJECT_TYPE_STATIC", "DM_PHYSICS_DDF__COLLISION_OBJECT_TYPE__COLLISION_OBJECT_TYPE_STATIC", 2 },
  { "COLLISION_OBJECT_TYPE_TRIGGER", "DM_PHYSICS_DDF__COLLISION_OBJECT_TYPE__COLLISION_OBJECT_TYPE_TRIGGER", 3 },
};
static const ProtobufCIntRange dm_physics_ddf__collision_object_type__value_ranges[] = {
{0, 0},{0, 4}
};
static const ProtobufCEnumValueIndex dm_physics_ddf__collision_object_type__enum_values_by_name[4] =
{
  { "COLLISION_OBJECT_TYPE_DYNAMIC", 0 },
  { "COLLISION_OBJECT_TYPE_KINEMATIC", 1 },
  { "COLLISION_OBJECT_TYPE_STATIC", 2 },
  { "COLLISION_OBJECT_TYPE_TRIGGER", 3 },
};
const ProtobufCEnumDescriptor dm_physics_ddf__collision_object_type__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "dmPhysicsDDF.CollisionObjectType",
  "CollisionObjectType",
  "DmPhysicsDDF__CollisionObjectType",
  "dmPhysicsDDF",
  4,
  dm_physics_ddf__collision_object_type__enum_values_by_number,
  4,
  dm_physics_ddf__collision_object_type__enum_values_by_name,
  1,
  dm_physics_ddf__collision_object_type__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
