/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: gamesys/sprite_ddf.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "gamesys/sprite_ddf.pb-c.h"
void   dm_game_system_ddf__sprite_desc__init
                     (DmGameSystemDDF__SpriteDesc         *message)
{
  static const DmGameSystemDDF__SpriteDesc init_value = DM_GAME_SYSTEM_DDF__SPRITE_DESC__INIT;
  *message = init_value;
}
size_t dm_game_system_ddf__sprite_desc__get_packed_size
                     (const DmGameSystemDDF__SpriteDesc *message)
{
  assert(message->base.descriptor == &dm_game_system_ddf__sprite_desc__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t dm_game_system_ddf__sprite_desc__pack
                     (const DmGameSystemDDF__SpriteDesc *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &dm_game_system_ddf__sprite_desc__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t dm_game_system_ddf__sprite_desc__pack_to_buffer
                     (const DmGameSystemDDF__SpriteDesc *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &dm_game_system_ddf__sprite_desc__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
DmGameSystemDDF__SpriteDesc *
       dm_game_system_ddf__sprite_desc__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (DmGameSystemDDF__SpriteDesc *)
     protobuf_c_message_unpack (&dm_game_system_ddf__sprite_desc__descriptor,
                                allocator, len, data);
}
void   dm_game_system_ddf__sprite_desc__free_unpacked
                     (DmGameSystemDDF__SpriteDesc *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &dm_game_system_ddf__sprite_desc__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   dm_game_system_ddf__play_animation__init
                     (DmGameSystemDDF__PlayAnimation         *message)
{
  static const DmGameSystemDDF__PlayAnimation init_value = DM_GAME_SYSTEM_DDF__PLAY_ANIMATION__INIT;
  *message = init_value;
}
size_t dm_game_system_ddf__play_animation__get_packed_size
                     (const DmGameSystemDDF__PlayAnimation *message)
{
  assert(message->base.descriptor == &dm_game_system_ddf__play_animation__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t dm_game_system_ddf__play_animation__pack
                     (const DmGameSystemDDF__PlayAnimation *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &dm_game_system_ddf__play_animation__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t dm_game_system_ddf__play_animation__pack_to_buffer
                     (const DmGameSystemDDF__PlayAnimation *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &dm_game_system_ddf__play_animation__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
DmGameSystemDDF__PlayAnimation *
       dm_game_system_ddf__play_animation__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (DmGameSystemDDF__PlayAnimation *)
     protobuf_c_message_unpack (&dm_game_system_ddf__play_animation__descriptor,
                                allocator, len, data);
}
void   dm_game_system_ddf__play_animation__free_unpacked
                     (DmGameSystemDDF__PlayAnimation *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &dm_game_system_ddf__play_animation__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   dm_game_system_ddf__animation_done__init
                     (DmGameSystemDDF__AnimationDone         *message)
{
  static const DmGameSystemDDF__AnimationDone init_value = DM_GAME_SYSTEM_DDF__ANIMATION_DONE__INIT;
  *message = init_value;
}
size_t dm_game_system_ddf__animation_done__get_packed_size
                     (const DmGameSystemDDF__AnimationDone *message)
{
  assert(message->base.descriptor == &dm_game_system_ddf__animation_done__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t dm_game_system_ddf__animation_done__pack
                     (const DmGameSystemDDF__AnimationDone *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &dm_game_system_ddf__animation_done__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t dm_game_system_ddf__animation_done__pack_to_buffer
                     (const DmGameSystemDDF__AnimationDone *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &dm_game_system_ddf__animation_done__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
DmGameSystemDDF__AnimationDone *
       dm_game_system_ddf__animation_done__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (DmGameSystemDDF__AnimationDone *)
     protobuf_c_message_unpack (&dm_game_system_ddf__animation_done__descriptor,
                                allocator, len, data);
}
void   dm_game_system_ddf__animation_done__free_unpacked
                     (DmGameSystemDDF__AnimationDone *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &dm_game_system_ddf__animation_done__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   dm_game_system_ddf__set_flip_horizontal__init
                     (DmGameSystemDDF__SetFlipHorizontal         *message)
{
  static const DmGameSystemDDF__SetFlipHorizontal init_value = DM_GAME_SYSTEM_DDF__SET_FLIP_HORIZONTAL__INIT;
  *message = init_value;
}
size_t dm_game_system_ddf__set_flip_horizontal__get_packed_size
                     (const DmGameSystemDDF__SetFlipHorizontal *message)
{
  assert(message->base.descriptor == &dm_game_system_ddf__set_flip_horizontal__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t dm_game_system_ddf__set_flip_horizontal__pack
                     (const DmGameSystemDDF__SetFlipHorizontal *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &dm_game_system_ddf__set_flip_horizontal__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t dm_game_system_ddf__set_flip_horizontal__pack_to_buffer
                     (const DmGameSystemDDF__SetFlipHorizontal *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &dm_game_system_ddf__set_flip_horizontal__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
DmGameSystemDDF__SetFlipHorizontal *
       dm_game_system_ddf__set_flip_horizontal__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (DmGameSystemDDF__SetFlipHorizontal *)
     protobuf_c_message_unpack (&dm_game_system_ddf__set_flip_horizontal__descriptor,
                                allocator, len, data);
}
void   dm_game_system_ddf__set_flip_horizontal__free_unpacked
                     (DmGameSystemDDF__SetFlipHorizontal *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &dm_game_system_ddf__set_flip_horizontal__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   dm_game_system_ddf__set_flip_vertical__init
                     (DmGameSystemDDF__SetFlipVertical         *message)
{
  static const DmGameSystemDDF__SetFlipVertical init_value = DM_GAME_SYSTEM_DDF__SET_FLIP_VERTICAL__INIT;
  *message = init_value;
}
size_t dm_game_system_ddf__set_flip_vertical__get_packed_size
                     (const DmGameSystemDDF__SetFlipVertical *message)
{
  assert(message->base.descriptor == &dm_game_system_ddf__set_flip_vertical__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t dm_game_system_ddf__set_flip_vertical__pack
                     (const DmGameSystemDDF__SetFlipVertical *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &dm_game_system_ddf__set_flip_vertical__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t dm_game_system_ddf__set_flip_vertical__pack_to_buffer
                     (const DmGameSystemDDF__SetFlipVertical *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &dm_game_system_ddf__set_flip_vertical__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
DmGameSystemDDF__SetFlipVertical *
       dm_game_system_ddf__set_flip_vertical__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (DmGameSystemDDF__SetFlipVertical *)
     protobuf_c_message_unpack (&dm_game_system_ddf__set_flip_vertical__descriptor,
                                allocator, len, data);
}
void   dm_game_system_ddf__set_flip_vertical__free_unpacked
                     (DmGameSystemDDF__SetFlipVertical *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &dm_game_system_ddf__set_flip_vertical__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCEnumValue dm_game_system_ddf__sprite_desc__blend_mode__enum_values_by_number[5] =
{
  { "BLEND_MODE_ALPHA", "DM_GAME_SYSTEM_DDF__SPRITE_DESC__BLEND_MODE__BLEND_MODE_ALPHA", 0 },
  { "BLEND_MODE_ADD", "DM_GAME_SYSTEM_DDF__SPRITE_DESC__BLEND_MODE__BLEND_MODE_ADD", 1 },
  { "BLEND_MODE_ADD_ALPHA", "DM_GAME_SYSTEM_DDF__SPRITE_DESC__BLEND_MODE__BLEND_MODE_ADD_ALPHA", 2 },
  { "BLEND_MODE_MULT", "DM_GAME_SYSTEM_DDF__SPRITE_DESC__BLEND_MODE__BLEND_MODE_MULT", 3 },
  { "BLEND_MODE_SCREEN", "DM_GAME_SYSTEM_DDF__SPRITE_DESC__BLEND_MODE__BLEND_MODE_SCREEN", 4 },
};
static const ProtobufCIntRange dm_game_system_ddf__sprite_desc__blend_mode__value_ranges[] = {
{0, 0},{0, 5}
};
static const ProtobufCEnumValueIndex dm_game_system_ddf__sprite_desc__blend_mode__enum_values_by_name[5] =
{
  { "BLEND_MODE_ADD", 1 },
  { "BLEND_MODE_ADD_ALPHA", 2 },
  { "BLEND_MODE_ALPHA", 0 },
  { "BLEND_MODE_MULT", 3 },
  { "BLEND_MODE_SCREEN", 4 },
};
const ProtobufCEnumDescriptor dm_game_system_ddf__sprite_desc__blend_mode__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "dmGameSystemDDF.SpriteDesc.BlendMode",
  "BlendMode",
  "DmGameSystemDDF__SpriteDesc__BlendMode",
  "dmGameSystemDDF",
  5,
  dm_game_system_ddf__sprite_desc__blend_mode__enum_values_by_number,
  5,
  dm_game_system_ddf__sprite_desc__blend_mode__enum_values_by_name,
  1,
  dm_game_system_ddf__sprite_desc__blend_mode__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const ProtobufCEnumValue dm_game_system_ddf__sprite_desc__size_mode__enum_values_by_number[2] =
{
  { "SIZE_MODE_MANUAL", "DM_GAME_SYSTEM_DDF__SPRITE_DESC__SIZE_MODE__SIZE_MODE_MANUAL", 0 },
  { "SIZE_MODE_AUTO", "DM_GAME_SYSTEM_DDF__SPRITE_DESC__SIZE_MODE__SIZE_MODE_AUTO", 1 },
};
static const ProtobufCIntRange dm_game_system_ddf__sprite_desc__size_mode__value_ranges[] = {
{0, 0},{0, 2}
};
static const ProtobufCEnumValueIndex dm_game_system_ddf__sprite_desc__size_mode__enum_values_by_name[2] =
{
  { "SIZE_MODE_AUTO", 1 },
  { "SIZE_MODE_MANUAL", 0 },
};
const ProtobufCEnumDescriptor dm_game_system_ddf__sprite_desc__size_mode__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "dmGameSystemDDF.SpriteDesc.SizeMode",
  "SizeMode",
  "DmGameSystemDDF__SpriteDesc__SizeMode",
  "dmGameSystemDDF",
  2,
  dm_game_system_ddf__sprite_desc__size_mode__enum_values_by_number,
  2,
  dm_game_system_ddf__sprite_desc__size_mode__enum_values_by_name,
  1,
  dm_game_system_ddf__sprite_desc__size_mode__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
char dm_game_system_ddf__sprite_desc__material__default_value[] = "/builtins/materials/sprite.material";
static const DmGameSystemDDF__SpriteDesc__BlendMode dm_game_system_ddf__sprite_desc__blend_mode__default_value = DM_GAME_SYSTEM_DDF__SPRITE_DESC__BLEND_MODE__BLEND_MODE_ALPHA;
static const DmGameSystemDDF__SpriteDesc__SizeMode dm_game_system_ddf__sprite_desc__size_mode__default_value = DM_GAME_SYSTEM_DDF__SPRITE_DESC__SIZE_MODE__SIZE_MODE_AUTO;
static const ProtobufCFieldDescriptor dm_game_system_ddf__sprite_desc__field_descriptors[7] =
{
  {
    "tile_set",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(DmGameSystemDDF__SpriteDesc, tile_set),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "default_animation",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(DmGameSystemDDF__SpriteDesc, default_animation),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "material",
    3,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(DmGameSystemDDF__SpriteDesc, material),
    NULL,
    &dm_game_system_ddf__sprite_desc__material__default_value,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "blend_mode",
    4,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_ENUM,
    offsetof(DmGameSystemDDF__SpriteDesc, has_blend_mode),
    offsetof(DmGameSystemDDF__SpriteDesc, blend_mode),
    &dm_game_system_ddf__sprite_desc__blend_mode__descriptor,
    &dm_game_system_ddf__sprite_desc__blend_mode__default_value,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "slice9",
    5,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(DmGameSystemDDF__SpriteDesc, slice9),
    &dm_math__vector4__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "size",
    6,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(DmGameSystemDDF__SpriteDesc, size),
    &dm_math__vector4__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "size_mode",
    7,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_ENUM,
    offsetof(DmGameSystemDDF__SpriteDesc, has_size_mode),
    offsetof(DmGameSystemDDF__SpriteDesc, size_mode),
    &dm_game_system_ddf__sprite_desc__size_mode__descriptor,
    &dm_game_system_ddf__sprite_desc__size_mode__default_value,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned dm_game_system_ddf__sprite_desc__field_indices_by_name[] = {
  3,   /* field[3] = blend_mode */
  1,   /* field[1] = default_animation */
  2,   /* field[2] = material */
  5,   /* field[5] = size */
  6,   /* field[6] = size_mode */
  4,   /* field[4] = slice9 */
  0,   /* field[0] = tile_set */
};
static const ProtobufCIntRange dm_game_system_ddf__sprite_desc__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 7 }
};
const ProtobufCMessageDescriptor dm_game_system_ddf__sprite_desc__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "dmGameSystemDDF.SpriteDesc",
  "SpriteDesc",
  "DmGameSystemDDF__SpriteDesc",
  "dmGameSystemDDF",
  sizeof(DmGameSystemDDF__SpriteDesc),
  7,
  dm_game_system_ddf__sprite_desc__field_descriptors,
  dm_game_system_ddf__sprite_desc__field_indices_by_name,
  1,  dm_game_system_ddf__sprite_desc__number_ranges,
  (ProtobufCMessageInit) dm_game_system_ddf__sprite_desc__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const float dm_game_system_ddf__play_animation__offset__default_value = 0;
static const float dm_game_system_ddf__play_animation__playback_rate__default_value = 1;
static const ProtobufCFieldDescriptor dm_game_system_ddf__play_animation__field_descriptors[3] =
{
  {
    "id",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    offsetof(DmGameSystemDDF__PlayAnimation, id),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "offset",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_FLOAT,
    offsetof(DmGameSystemDDF__PlayAnimation, has_offset),
    offsetof(DmGameSystemDDF__PlayAnimation, offset),
    NULL,
    &dm_game_system_ddf__play_animation__offset__default_value,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "playback_rate",
    3,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_FLOAT,
    offsetof(DmGameSystemDDF__PlayAnimation, has_playback_rate),
    offsetof(DmGameSystemDDF__PlayAnimation, playback_rate),
    NULL,
    &dm_game_system_ddf__play_animation__playback_rate__default_value,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned dm_game_system_ddf__play_animation__field_indices_by_name[] = {
  0,   /* field[0] = id */
  1,   /* field[1] = offset */
  2,   /* field[2] = playback_rate */
};
static const ProtobufCIntRange dm_game_system_ddf__play_animation__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor dm_game_system_ddf__play_animation__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "dmGameSystemDDF.PlayAnimation",
  "PlayAnimation",
  "DmGameSystemDDF__PlayAnimation",
  "dmGameSystemDDF",
  sizeof(DmGameSystemDDF__PlayAnimation),
  3,
  dm_game_system_ddf__play_animation__field_descriptors,
  dm_game_system_ddf__play_animation__field_indices_by_name,
  1,  dm_game_system_ddf__play_animation__number_ranges,
  (ProtobufCMessageInit) dm_game_system_ddf__play_animation__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor dm_game_system_ddf__animation_done__field_descriptors[2] =
{
  {
    "current_tile",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(DmGameSystemDDF__AnimationDone, current_tile),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "id",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    offsetof(DmGameSystemDDF__AnimationDone, id),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned dm_game_system_ddf__animation_done__field_indices_by_name[] = {
  0,   /* field[0] = current_tile */
  1,   /* field[1] = id */
};
static const ProtobufCIntRange dm_game_system_ddf__animation_done__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor dm_game_system_ddf__animation_done__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "dmGameSystemDDF.AnimationDone",
  "AnimationDone",
  "DmGameSystemDDF__AnimationDone",
  "dmGameSystemDDF",
  sizeof(DmGameSystemDDF__AnimationDone),
  2,
  dm_game_system_ddf__animation_done__field_descriptors,
  dm_game_system_ddf__animation_done__field_indices_by_name,
  1,  dm_game_system_ddf__animation_done__number_ranges,
  (ProtobufCMessageInit) dm_game_system_ddf__animation_done__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor dm_game_system_ddf__set_flip_horizontal__field_descriptors[1] =
{
  {
    "flip",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(DmGameSystemDDF__SetFlipHorizontal, flip),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned dm_game_system_ddf__set_flip_horizontal__field_indices_by_name[] = {
  0,   /* field[0] = flip */
};
static const ProtobufCIntRange dm_game_system_ddf__set_flip_horizontal__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor dm_game_system_ddf__set_flip_horizontal__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "dmGameSystemDDF.SetFlipHorizontal",
  "SetFlipHorizontal",
  "DmGameSystemDDF__SetFlipHorizontal",
  "dmGameSystemDDF",
  sizeof(DmGameSystemDDF__SetFlipHorizontal),
  1,
  dm_game_system_ddf__set_flip_horizontal__field_descriptors,
  dm_game_system_ddf__set_flip_horizontal__field_indices_by_name,
  1,  dm_game_system_ddf__set_flip_horizontal__number_ranges,
  (ProtobufCMessageInit) dm_game_system_ddf__set_flip_horizontal__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor dm_game_system_ddf__set_flip_vertical__field_descriptors[1] =
{
  {
    "flip",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(DmGameSystemDDF__SetFlipVertical, flip),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned dm_game_system_ddf__set_flip_vertical__field_indices_by_name[] = {
  0,   /* field[0] = flip */
};
static const ProtobufCIntRange dm_game_system_ddf__set_flip_vertical__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor dm_game_system_ddf__set_flip_vertical__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "dmGameSystemDDF.SetFlipVertical",
  "SetFlipVertical",
  "DmGameSystemDDF__SetFlipVertical",
  "dmGameSystemDDF",
  sizeof(DmGameSystemDDF__SetFlipVertical),
  1,
  dm_game_system_ddf__set_flip_vertical__field_descriptors,
  dm_game_system_ddf__set_flip_vertical__field_indices_by_name,
  1,  dm_game_system_ddf__set_flip_vertical__number_ranges,
  (ProtobufCMessageInit) dm_game_system_ddf__set_flip_vertical__init,
  NULL,NULL,NULL    /* reserved[123] */
};
