/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: gamesys/texture_set_ddf.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "gamesys/texture_set_ddf.pb-c.h"
void   dm_game_system_ddf__texture_set_animation__init
                     (DmGameSystemDDF__TextureSetAnimation         *message)
{
  static const DmGameSystemDDF__TextureSetAnimation init_value = DM_GAME_SYSTEM_DDF__TEXTURE_SET_ANIMATION__INIT;
  *message = init_value;
}
size_t dm_game_system_ddf__texture_set_animation__get_packed_size
                     (const DmGameSystemDDF__TextureSetAnimation *message)
{
  assert(message->base.descriptor == &dm_game_system_ddf__texture_set_animation__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t dm_game_system_ddf__texture_set_animation__pack
                     (const DmGameSystemDDF__TextureSetAnimation *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &dm_game_system_ddf__texture_set_animation__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t dm_game_system_ddf__texture_set_animation__pack_to_buffer
                     (const DmGameSystemDDF__TextureSetAnimation *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &dm_game_system_ddf__texture_set_animation__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
DmGameSystemDDF__TextureSetAnimation *
       dm_game_system_ddf__texture_set_animation__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (DmGameSystemDDF__TextureSetAnimation *)
     protobuf_c_message_unpack (&dm_game_system_ddf__texture_set_animation__descriptor,
                                allocator, len, data);
}
void   dm_game_system_ddf__texture_set_animation__free_unpacked
                     (DmGameSystemDDF__TextureSetAnimation *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &dm_game_system_ddf__texture_set_animation__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   dm_game_system_ddf__sprite_geometry__init
                     (DmGameSystemDDF__SpriteGeometry         *message)
{
  static const DmGameSystemDDF__SpriteGeometry init_value = DM_GAME_SYSTEM_DDF__SPRITE_GEOMETRY__INIT;
  *message = init_value;
}
size_t dm_game_system_ddf__sprite_geometry__get_packed_size
                     (const DmGameSystemDDF__SpriteGeometry *message)
{
  assert(message->base.descriptor == &dm_game_system_ddf__sprite_geometry__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t dm_game_system_ddf__sprite_geometry__pack
                     (const DmGameSystemDDF__SpriteGeometry *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &dm_game_system_ddf__sprite_geometry__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t dm_game_system_ddf__sprite_geometry__pack_to_buffer
                     (const DmGameSystemDDF__SpriteGeometry *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &dm_game_system_ddf__sprite_geometry__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
DmGameSystemDDF__SpriteGeometry *
       dm_game_system_ddf__sprite_geometry__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (DmGameSystemDDF__SpriteGeometry *)
     protobuf_c_message_unpack (&dm_game_system_ddf__sprite_geometry__descriptor,
                                allocator, len, data);
}
void   dm_game_system_ddf__sprite_geometry__free_unpacked
                     (DmGameSystemDDF__SpriteGeometry *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &dm_game_system_ddf__sprite_geometry__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   dm_game_system_ddf__texture_set__init
                     (DmGameSystemDDF__TextureSet         *message)
{
  static const DmGameSystemDDF__TextureSet init_value = DM_GAME_SYSTEM_DDF__TEXTURE_SET__INIT;
  *message = init_value;
}
size_t dm_game_system_ddf__texture_set__get_packed_size
                     (const DmGameSystemDDF__TextureSet *message)
{
  assert(message->base.descriptor == &dm_game_system_ddf__texture_set__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t dm_game_system_ddf__texture_set__pack
                     (const DmGameSystemDDF__TextureSet *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &dm_game_system_ddf__texture_set__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t dm_game_system_ddf__texture_set__pack_to_buffer
                     (const DmGameSystemDDF__TextureSet *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &dm_game_system_ddf__texture_set__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
DmGameSystemDDF__TextureSet *
       dm_game_system_ddf__texture_set__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (DmGameSystemDDF__TextureSet *)
     protobuf_c_message_unpack (&dm_game_system_ddf__texture_set__descriptor,
                                allocator, len, data);
}
void   dm_game_system_ddf__texture_set__free_unpacked
                     (DmGameSystemDDF__TextureSet *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &dm_game_system_ddf__texture_set__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const uint32_t dm_game_system_ddf__texture_set_animation__fps__default_value = 30u;
static const DmGameSystemDDF__Playback dm_game_system_ddf__texture_set_animation__playback__default_value = DM_GAME_SYSTEM_DDF__PLAYBACK__PLAYBACK_ONCE_FORWARD;
static const uint32_t dm_game_system_ddf__texture_set_animation__flip_horizontal__default_value = 0u;
static const uint32_t dm_game_system_ddf__texture_set_animation__flip_vertical__default_value = 0u;
static const uint32_t dm_game_system_ddf__texture_set_animation__is_animation__default_value = 0u;
static const ProtobufCFieldDescriptor dm_game_system_ddf__texture_set_animation__field_descriptors[10] =
{
  {
    "id",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(DmGameSystemDDF__TextureSetAnimation, id),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "width",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(DmGameSystemDDF__TextureSetAnimation, width),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "height",
    3,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(DmGameSystemDDF__TextureSetAnimation, height),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "start",
    4,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(DmGameSystemDDF__TextureSetAnimation, start),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "end",
    5,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(DmGameSystemDDF__TextureSetAnimation, end),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "fps",
    6,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(DmGameSystemDDF__TextureSetAnimation, has_fps),
    offsetof(DmGameSystemDDF__TextureSetAnimation, fps),
    NULL,
    &dm_game_system_ddf__texture_set_animation__fps__default_value,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "playback",
    7,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_ENUM,
    offsetof(DmGameSystemDDF__TextureSetAnimation, has_playback),
    offsetof(DmGameSystemDDF__TextureSetAnimation, playback),
    &dm_game_system_ddf__playback__descriptor,
    &dm_game_system_ddf__texture_set_animation__playback__default_value,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "flip_horizontal",
    8,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(DmGameSystemDDF__TextureSetAnimation, has_flip_horizontal),
    offsetof(DmGameSystemDDF__TextureSetAnimation, flip_horizontal),
    NULL,
    &dm_game_system_ddf__texture_set_animation__flip_horizontal__default_value,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "flip_vertical",
    9,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(DmGameSystemDDF__TextureSetAnimation, has_flip_vertical),
    offsetof(DmGameSystemDDF__TextureSetAnimation, flip_vertical),
    NULL,
    &dm_game_system_ddf__texture_set_animation__flip_vertical__default_value,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "is_animation",
    10,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(DmGameSystemDDF__TextureSetAnimation, has_is_animation),
    offsetof(DmGameSystemDDF__TextureSetAnimation, is_animation),
    NULL,
    &dm_game_system_ddf__texture_set_animation__is_animation__default_value,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned dm_game_system_ddf__texture_set_animation__field_indices_by_name[] = {
  4,   /* field[4] = end */
  7,   /* field[7] = flip_horizontal */
  8,   /* field[8] = flip_vertical */
  5,   /* field[5] = fps */
  2,   /* field[2] = height */
  0,   /* field[0] = id */
  9,   /* field[9] = is_animation */
  6,   /* field[6] = playback */
  3,   /* field[3] = start */
  1,   /* field[1] = width */
};
static const ProtobufCIntRange dm_game_system_ddf__texture_set_animation__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 10 }
};
const ProtobufCMessageDescriptor dm_game_system_ddf__texture_set_animation__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "dmGameSystemDDF.TextureSetAnimation",
  "TextureSetAnimation",
  "DmGameSystemDDF__TextureSetAnimation",
  "dmGameSystemDDF",
  sizeof(DmGameSystemDDF__TextureSetAnimation),
  10,
  dm_game_system_ddf__texture_set_animation__field_descriptors,
  dm_game_system_ddf__texture_set_animation__field_indices_by_name,
  1,  dm_game_system_ddf__texture_set_animation__number_ranges,
  (ProtobufCMessageInit) dm_game_system_ddf__texture_set_animation__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor dm_game_system_ddf__sprite_geometry__field_descriptors[5] =
{
  {
    "width",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(DmGameSystemDDF__SpriteGeometry, width),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "height",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(DmGameSystemDDF__SpriteGeometry, height),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "vertices",
    3,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_FLOAT,
    offsetof(DmGameSystemDDF__SpriteGeometry, n_vertices),
    offsetof(DmGameSystemDDF__SpriteGeometry, vertices),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "uvs",
    4,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_FLOAT,
    offsetof(DmGameSystemDDF__SpriteGeometry, n_uvs),
    offsetof(DmGameSystemDDF__SpriteGeometry, uvs),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "indices",
    5,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(DmGameSystemDDF__SpriteGeometry, n_indices),
    offsetof(DmGameSystemDDF__SpriteGeometry, indices),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned dm_game_system_ddf__sprite_geometry__field_indices_by_name[] = {
  1,   /* field[1] = height */
  4,   /* field[4] = indices */
  3,   /* field[3] = uvs */
  2,   /* field[2] = vertices */
  0,   /* field[0] = width */
};
static const ProtobufCIntRange dm_game_system_ddf__sprite_geometry__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 5 }
};
const ProtobufCMessageDescriptor dm_game_system_ddf__sprite_geometry__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "dmGameSystemDDF.SpriteGeometry",
  "SpriteGeometry",
  "DmGameSystemDDF__SpriteGeometry",
  "dmGameSystemDDF",
  sizeof(DmGameSystemDDF__SpriteGeometry),
  5,
  dm_game_system_ddf__sprite_geometry__field_descriptors,
  dm_game_system_ddf__sprite_geometry__field_indices_by_name,
  1,  dm_game_system_ddf__sprite_geometry__number_ranges,
  (ProtobufCMessageInit) dm_game_system_ddf__sprite_geometry__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor dm_game_system_ddf__texture_set__field_descriptors[13] =
{
  {
    "texture",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(DmGameSystemDDF__TextureSet, texture),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "animations",
    2,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(DmGameSystemDDF__TextureSet, n_animations),
    offsetof(DmGameSystemDDF__TextureSet, animations),
    &dm_game_system_ddf__texture_set_animation__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "convex_hulls",
    3,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(DmGameSystemDDF__TextureSet, n_convex_hulls),
    offsetof(DmGameSystemDDF__TextureSet, convex_hulls),
    &dm_game_system_ddf__convex_hull__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "tile_width",
    4,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(DmGameSystemDDF__TextureSet, has_tile_width),
    offsetof(DmGameSystemDDF__TextureSet, tile_width),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "tile_height",
    5,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(DmGameSystemDDF__TextureSet, has_tile_height),
    offsetof(DmGameSystemDDF__TextureSet, tile_height),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "tile_count",
    6,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(DmGameSystemDDF__TextureSet, has_tile_count),
    offsetof(DmGameSystemDDF__TextureSet, tile_count),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "collision_hull_points",
    16,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_FLOAT,
    offsetof(DmGameSystemDDF__TextureSet, n_collision_hull_points),
    offsetof(DmGameSystemDDF__TextureSet, collision_hull_points),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "collision_groups",
    17,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_STRING,
    offsetof(DmGameSystemDDF__TextureSet, n_collision_groups),
    offsetof(DmGameSystemDDF__TextureSet, collision_groups),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "tex_coords",
    18,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    offsetof(DmGameSystemDDF__TextureSet, tex_coords),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "tex_dims",
    19,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BYTES,
    offsetof(DmGameSystemDDF__TextureSet, has_tex_dims),
    offsetof(DmGameSystemDDF__TextureSet, tex_dims),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "geometries",
    20,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(DmGameSystemDDF__TextureSet, n_geometries),
    offsetof(DmGameSystemDDF__TextureSet, geometries),
    &dm_game_system_ddf__sprite_geometry__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "use_geometries",
    21,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(DmGameSystemDDF__TextureSet, has_use_geometries),
    offsetof(DmGameSystemDDF__TextureSet, use_geometries),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "frame_indices",
    22,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(DmGameSystemDDF__TextureSet, n_frame_indices),
    offsetof(DmGameSystemDDF__TextureSet, frame_indices),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned dm_game_system_ddf__texture_set__field_indices_by_name[] = {
  1,   /* field[1] = animations */
  7,   /* field[7] = collision_groups */
  6,   /* field[6] = collision_hull_points */
  2,   /* field[2] = convex_hulls */
  12,   /* field[12] = frame_indices */
  10,   /* field[10] = geometries */
  8,   /* field[8] = tex_coords */
  9,   /* field[9] = tex_dims */
  0,   /* field[0] = texture */
  5,   /* field[5] = tile_count */
  4,   /* field[4] = tile_height */
  3,   /* field[3] = tile_width */
  11,   /* field[11] = use_geometries */
};
static const ProtobufCIntRange dm_game_system_ddf__texture_set__number_ranges[2 + 1] =
{
  { 1, 0 },
  { 16, 6 },
  { 0, 13 }
};
const ProtobufCMessageDescriptor dm_game_system_ddf__texture_set__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "dmGameSystemDDF.TextureSet",
  "TextureSet",
  "DmGameSystemDDF__TextureSet",
  "dmGameSystemDDF",
  sizeof(DmGameSystemDDF__TextureSet),
  13,
  dm_game_system_ddf__texture_set__field_descriptors,
  dm_game_system_ddf__texture_set__field_indices_by_name,
  2,  dm_game_system_ddf__texture_set__number_ranges,
  (ProtobufCMessageInit) dm_game_system_ddf__texture_set__init,
  NULL,NULL,NULL    /* reserved[123] */
};
